# Generated by Django 4.1.3 on 2022-11-21 13:56

from django.db import migrations
from django.db import models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('none', 'Not Given'), ('m', 'Male'), (
                    'f', 'Female'), ('d', 'Diverse')], default='none', max_length=4, verbose_name='gender')),
            ],
            options={
                'verbose_name': 'Project Participant',
                'verbose_name_plural': 'Project Participants',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='statistic',
            field=models.JSONField(
                default=projects.models.Project.statistic_default),
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(
                to='projects.projectparticipant', verbose_name='Project Participants'),
        ),
    ]
