# Generated by Django 4.1.3 on 2022-12-19 10:22

from django.db import migrations
from django.db import models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media_education_supervisors',
            field=models.ManyToManyField(
                to='projects.mediaeducationsupervisor', verbose_name='Media education supervisors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.ForeignKey(default=projects.models.default_category, on_delete=django.db.models.deletion.CASCADE,
                                    to='projects.projectcategory', verbose_name='Project category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='projects.projectleader', verbose_name='Project leader'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_group',
            field=models.ForeignKey(default=projects.models.default_target_group,
                                    on_delete=django.db.models.deletion.CASCADE, to='projects.targetgroup', verbose_name='Target group'),
        ),
    ]
