# Generated by Django 4.1.3 on 2022-12-20 09:06

from django.db import migrations
from django.db import models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_media_education_supervisors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date(
                2022, 12, 20), verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.DurationField(
                blank=True, help_text='Project time in minutes', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='media_education_supervisors',
            field=models.ManyToManyField(
                blank=True, to='projects.mediaeducationsupervisor', verbose_name='Media education supervisors'),
        ),
    ]
