# Generated by Django 4.1 on 2022-08-22 13:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_tn_0_bis_6_project_tn_7_bis_10"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tn_11_bis_14",
            field=models.IntegerField(default=0, verbose_name="11-14 Jahre"),
        ),
        migrations.AddField(
            model_name="project",
            name="tn_15_bis_18",
            field=models.IntegerField(default=0, verbose_name="15-18 Jahre"),
        ),
        migrations.AddField(
            model_name="project",
            name="tn_19_bis_34",
            field=models.IntegerField(default=0, verbose_name="19-34 Jahre"),
        ),
        migrations.AddField(
            model_name="project",
            name="tn_35_bis_50",
            field=models.IntegerField(default=0, verbose_name="35-50 Jahre"),
        ),
        migrations.AddField(
            model_name="project",
            name="tn_51_bis_65",
            field=models.IntegerField(default=0, verbose_name="51-65 Jahre"),
        ),
        migrations.AddField(
            model_name="project",
            name="tn_age_not_given",
            field=models.IntegerField(default=0, verbose_name="ohne Angabe"),
        ),
        migrations.AddField(
            model_name="project",
            name="tn_female",
            field=models.IntegerField(default=0, verbose_name="weiblich"),
        ),
        migrations.AddField(
            model_name="project",
            name="tn_gender_not_given",
            field=models.IntegerField(default=0, verbose_name="ohne Angabe"),
        ),
        migrations.AddField(
            model_name="project",
            name="tn_male",
            field=models.IntegerField(default=0, verbose_name="männlich"),
        ),
        migrations.AddField(
            model_name="project",
            name="tn_ueber_65",
            field=models.IntegerField(default=0, verbose_name="über 65 Jahre"),
        ),
    ]
