# Generated by Django 4.1.2 on 2022-11-18 15:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.JSONField(verbose_name='participants'),
        ),
    ]
