# Generated by Django 4.1.3 on 2022-11-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectparticipant_project_statistic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tn_0_bis_6',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tn_11_bis_14',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tn_15_bis_18',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tn_19_bis_34',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tn_35_bis_50',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tn_51_bis_65',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tn_7_bis_10',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tn_age_not_given',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tn_diverse',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tn_female',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tn_gender_not_given',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tn_male',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tn_ueber_65',
        ),
    ]
