# Generated by Django 4.0.5 on 2022-09-01 07:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_tn_11_bis_14_project_tn_15_bis_18_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='media_education_supervisor',
        ),
        migrations.AddField(
            model_name='project',
            name='media_education_supervisors',
            field=models.ManyToManyField(
                null=True, to='projects.mediaeducationsupervisor'),
        ),
    ]
