# Generated by Django 4.1.3 on 2022-11-21 16:44

from django.db import migrations
from django.db import models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_tn_0_bis_6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='statistic',
            field=models.JSONField(
                blank=True, default=projects.models.Project.statistic_default, verbose_name='Gender and Age'),
        ),
        migrations.AlterField(
            model_name='projectparticipant',
            name='age',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='projectparticipant',
            name='gender',
            field=models.CharField(choices=[('none', 'Not Given'), ('m', 'Male'), ('f', 'Female'), (
                'd', 'Diverse')], default='none', max_length=4, verbose_name='Gender'),
        ),
    ]
