# Generated by Django 4.1.3 on 2022-12-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_media_education_supervisors'),
        ('projects', '0003_remove_project_begin_date_remove_project_end_date_and_more'),
    ]

    operations = [
    ]
