# Generated by Django 4.0.5 on 2022-09-01 07:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_media_education_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media_education_supervisors',
            field=models.ManyToManyField(
                to='projects.mediaeducationsupervisor'),
        ),
    ]
