# Generated by Django 4.1.3 on 2023-03-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_merge_20221221_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.DurationField(blank=True, help_text='Format: hh:mm:ss or mm:ss', null=True, verbose_name='Duration'),
        ),
    ]
