# Generated by Django 4.1.7 on 2023-08-22 10:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
    ]
