# Generated by Django 4.0.5 on 2022-09-14 09:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_tn_diverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaeducationsupervisor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(
                max_length=255, verbose_name='Project category'),
        ),
        migrations.AlterField(
            model_name='projectleader',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='targetgroup',
            name='name',
            field=models.CharField(
                max_length=255, verbose_name='Target group'),
        ),
    ]
