# Generated by Django 4.1.3 on 2022-11-21 07:15

from django.db import migrations
from django.db import models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='participants',
            field=models.JSONField(
                default=projects.models.Project._participants_structure, verbose_name='participants'),
        ),
    ]
