# Generated by Django 4.0.5 on 2022-09-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_mediaeducationsupervisor_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['id'], 'verbose_name': 'Project category',
                     'verbose_name_plural': 'Project categories'},
        ),
        migrations.AlterModelOptions(
            name='targetgroup',
            options={'ordering': [
                'id'], 'verbose_name': 'Target group', 'verbose_name_plural': 'Target groups'},
        ),
    ]
