# Generated by Django 4.0.5 on 2022-09-27 14:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_democracy_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='begin_date',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.DurationField(
                blank=True, help_text='Total amount of time spend.', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(verbose_name='End date'),
        ),
    ]
