# Generated by Django 4.0.5 on 2022-08-31 11:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_date', models.DateTimeField(
                    verbose_name='Broadcast Date')),
                ('live', models.BooleanField(verbose_name='Is live')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
            },
        ),
    ]
