# Generated by Django 4.0.5 on 2022-08-25 09:16

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0012_alter_licenserequest_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_dae', models.DateTimeField(
                    verbose_name='Broadcast Date')),
                ('live', models.BooleanField(verbose_name='Is live')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='licenses.licenserequest', verbose_name='License')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
            },
        ),
    ]
