# Generated by Django 4.1.7 on 2024-02-10 11:01

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0001_initial'),
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licenses.license', verbose_name='License'),
        ),
    ]
