# Generated by Django 4.0.5 on 2022-09-07 09:29

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributions', '0001_initial'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='licenses.licenserequest', verbose_name='License'),
        ),
    ]
