# Generated by Django 5.2.5 on 2025-10-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='broadcast_date',
            field=models.DateTimeField(db_index=True, verbose_name='Broadcast Date'),
        ),
    ]
