# Generated by Django 4.0.5 on 2022-09-07 13:33

from django.db import migrations
from django.db import models
import contributions.models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_disaimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaimport',
            name='imported',
            field=models.BooleanField(default=False, verbose_name='Imported'),
        ),
        migrations.AlterField(
            model_name='disaimport',
            name='file',
            field=models.FileField(upload_to=contributions.models.DisaImport.timestamp_path, validators=[
                                   django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='DISA export file'),
        ),
    ]
