# Generated by Django 5.2.7 on 2025-11-27 19:25

import contributions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_alter_contribution_broadcast_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaimport',
            name='import_from_date',
            field=models.DateField(blank=True, help_text='Only import contributions from this date onwards.', null=True, verbose_name='Import from date'),
        ),
        migrations.AlterField(
            model_name='disaimport',
            name='file',
            field=models.FileField(upload_to=contributions.models.DisaImport.timestamp_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls'])], verbose_name='DISA export file'),
        ),
    ]
