# Generated by Django 4.0.5 on 2022-09-12 13:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_disaimport_imported_alter_disaimport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaimport',
            name='imported',
            field=models.BooleanField(
                default=False, help_text='Just marking the file as imported does not import the file!', verbose_name='Imported'),
        ),
    ]
