# Generated by hand for initial rental app migration

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project name')),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('requested_start_date', models.DateTimeField(verbose_name='Requested start date')),
                ('requested_end_date', models.DateTimeField(verbose_name='Requested end date')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual start date')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Actual end date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reserved', 'Reserved'), ('issued', 'Issued'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rentals', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Rental request',
                'verbose_name_plural': 'Rental requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_template', models.BooleanField(default=False, verbose_name='Is template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Equipment set',
                'verbose_name_plural': 'Equipment sets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='Quantity requested')),
                ('quantity_issued', models.PositiveIntegerField(default=0, verbose_name='Quantity issued')),
                ('quantity_returned', models.PositiveIntegerField(default=0, verbose_name='Quantity returned')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem', verbose_name='Inventory item')),
                ('rental_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rental.rentalrequest', verbose_name='Rental request')),
            ],
            options={
                'verbose_name': 'Rental item',
                'verbose_name_plural': 'Rental items',
            },
        ),
        migrations.CreateModel(
            name='EquipmentSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('is_required', models.BooleanField(default=True, verbose_name='Is required')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('equipment_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rental.equipmentset', verbose_name='Equipment set')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem', verbose_name='Inventory item')),
            ],
            options={
                'verbose_name': 'Equipment set item',
                'verbose_name_plural': 'Equipment set items',
            },
        ),
    ]
