# Generated by Django 4.1.7 on 2025-08-16 16:32

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_remove_inventoryitem_object_type_and_more'),
        ('rental', '0002_rentaltransaction_rentalissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalitem',
            name='inventory_item',
            field=models.ForeignKey(help_text='Search by number, description, manufacturer', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem', verbose_name='Inventory item'),
        ),
    ]
