# Generated by Django 4.1.7 on 2025-08-16 21:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_rentalitem_inventory_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProcessProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Rental Process',
                'verbose_name_plural': 'Rental Process',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rental.rentalrequest',),
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='actual_return_date',
            field=models.DateTimeField(blank=True, help_text='Date when the item was actually returned (auto-filled on return)', null=True, verbose_name='Actual return date'),
        ),
    ]
