# Generated by Django 4.1.7 on 2025-08-16 23:10

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_add_actual_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Room name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rentalrequest',
            name='rental_type',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('room', 'Room'), ('mixed', 'Equipment and Room')], default='equipment', help_text='Type of rental: equipment, room, or both', max_length=20, verbose_name='Rental type'),
        ),
        migrations.CreateModel(
            name='RoomRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_count', models.PositiveIntegerField(help_text='Number of people using the room', verbose_name='Number of people')),
                ('notes', models.TextField(blank=True, help_text='Additional notes for room rental', verbose_name='Notes')),
                ('rental_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_rentals', to='rental.rentalrequest', verbose_name='Rental request')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room rental',
                'verbose_name_plural': 'Room rentals',
                'unique_together': {('rental_request', 'room')},
            },
        ),
    ]
