# Generated by Django 4.1.7 on 2025-08-16 23:10

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_room_rentalrequest_rental_type_roomrental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaltransaction',
            name='rental_item',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transactions',
                to='rental.rentalitem',
                verbose_name='Rental item'
            ),
        ),
        migrations.AddField(
            model_name='rentaltransaction',
            name='room',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transactions',
                to='rental.room',
                verbose_name='Room'
            ),
        ),
    ]
