# Generated by Django 4.1.7 on 2025-08-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_rentaltransaction_room'),
    ]

    operations = [
        # This is a migration for Python methods that don't require DB changes
        # Methods is_available_for_time and get_conflicting_rentals added to Room model
    ]
