# Generated by Django 4.1.7 on 2025-08-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_rentaltransaction_room'),
    ]

    operations = [
        # Это миграция для методов Python, которые не требуют изменений в БД
        # Методы is_available_for_time и get_conflicting_rentals добавлены в модель Room
    ]
