# Generated by Django 4.1.7 on 2025-08-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_room_availability_check'),
    ]

    operations = [
        # This is a migration for Python methods that don't require DB changes
        # Added past time validation in API and model
    ]
