# Generated by Django 4.1.7 on 2025-08-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_room_availability_check'),
    ]

    operations = [
        # Это миграция для методов Python, которые не требуют изменений в БД
        # Добавлена валидация времени в прошлом в API и модели
    ]
