# Generated by Django 5.2.5 on 2025-09-20 00:47

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_merge_20250819_1733'),
        ('rental', '0008_past_time_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the equipment template (e.g., "Concert Setup", "Workshop Equipment")', max_length=255, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of what this template is used for', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Equipment Template',
                'verbose_name_plural': 'Equipment Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Default quantity for this item in the template', verbose_name='Quantity')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem', verbose_name='Inventory Item')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rental.equipmenttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template Item',
                'verbose_name_plural': 'Template Items',
                'unique_together': {('template', 'inventory_item')},
            },
        ),
    ]
