# Generated by Django 5.2.7 on 2025-11-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_equipmenttemplate_equipmenttemplateitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrental',
            name='requested_end_date',
            field=models.DateTimeField(blank=True, help_text='Room rental end date. If not specified, uses rental request end date.', null=True, verbose_name='Requested end date'),
        ),
        migrations.AddField(
            model_name='roomrental',
            name='requested_start_date',
            field=models.DateTimeField(blank=True, help_text='Room rental start date. If not specified, uses rental request start date.', null=True, verbose_name='Requested start date'),
        ),
    ]

