# Generated by Django 5.2.7 on 2026-01-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_roomrental_nextcloud_event_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_request_requires_approval', models.BooleanField(default=False, help_text='Enable email-based approval workflow for user-created rental requests', verbose_name='User Request Requires Approval')),
                ('site_base_url', models.URLField(blank=True, help_text='Base URL for approval links in emails (must match your production domain)', verbose_name='Site Base URL')),
                ('request_url_template', models.CharField(blank=True, help_text='User-facing rental request URL template (use {rental_id} placeholder)', max_length=500, verbose_name='Rental Request URL Template')),
                ('approval_recipient_emails', models.TextField(blank=True, help_text='Comma-separated list of admin email addresses to notify (optional, if empty all staff users will be notified)', verbose_name='Approval Recipient Emails')),
                ('approval_token_max_age_seconds', models.IntegerField(default=604800, help_text='Token expiration time for approve/deny links in seconds', verbose_name='Approval Token Max Age (seconds)')),
            ],
            options={
                'verbose_name': 'Rental Configuration',
                'verbose_name_plural': 'Rental Configuration',
            },
        ),
    ]
