# Generated by Django 5.2.7 on 2026-04-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_inspectionimport_file_and_more'),
        ('rental', '0014_rentalitem_pick_list_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalconfig',
            name='employee_organizations',
            field=models.ManyToManyField(blank=True, related_name='rental_config_employee', to='inventory.organization', verbose_name='Employee organizations'),
        ),
        migrations.AddField(
            model_name='rentalconfig',
            name='member_organizations',
            field=models.ManyToManyField(blank=True, related_name='rental_config_member', to='inventory.organization', verbose_name='Member organizations'),
        ),
        migrations.AddField(
            model_name='rentalconfig',
            name='user_organizations',
            field=models.ManyToManyField(blank=True, related_name='rental_config_user', to='inventory.organization', verbose_name='User organizations'),
        ),
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reserved', 'Reserved'), ('issued', 'Issued'), ('returned', 'Returned'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
