# Generated by Django 5.2.7 on 2026-06-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0018_signingsession_owner_and_token_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalconfig',
            name='auto_reminder_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic return reminder emails for issued rentals', verbose_name='Automatic Return Reminders'),
        ),
        migrations.AddField(
            model_name='rentalconfig',
            name='auto_reminder_hours_before',
            field=models.IntegerField(default=24, help_text='Send reminder this many hours before the requested return date', verbose_name='Reminder Hours Before Return'),
        ),
        migrations.AlterField(
            model_name='rentalsigningsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
