# Generated by Django 6.0.6 on 2026-07-06 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_rentalrequest_auto_return_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalconfig',
            name='show_item_photos',
            field=models.BooleanField(default=False, help_text='Show inventory item photos on the rental process and dashboard pages', verbose_name='Show item photos'),
        ),
        migrations.AddField(
            model_name='rentalconfig',
            name='show_room_photos',
            field=models.BooleanField(default=False, help_text='Show room photos on the rental process page', verbose_name='Show room photos'),
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_photos/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room photo',
                'verbose_name_plural': 'Room photos',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
