# Generated by Django 6.0.6 on 2026-07-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_inventoryitem_notes'),
        ('rental', '0021_rentalconfig_show_item_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalconfig',
            name='rental_only_organizations',
            field=models.ManyToManyField(blank=True, related_name='rental_config_rental_only', to='inventory.organization', verbose_name='Rental only organizations'),
        ),
    ]
