# Generated by Django 6.0.6 on 2026-08-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0022_rentalconfig_rental_only_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalconfig',
            name='scan_sound_enabled',
            field=models.BooleanField(default=False, help_text='Play a short tone when a barcode scan succeeds or fails. Off by default, because a shared counter gets noisy.', verbose_name='Scanner feedback sound'),
        ),
    ]
