# Generated by Django 6.0.6 on 2026-09-16 12:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0023_rental_scan_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalconfig',
            name='label_gap_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('2.0'), help_text='Distance between two labels on the roll. Measure it: a wrong value makes the printer feed past the next label.', max_digits=4, verbose_name='Label gap (mm)'),
        ),
        migrations.AddField(
            model_name='rentalconfig',
            name='label_printer_density',
            field=models.PositiveSmallIntegerField(default=8, help_text='Heat setting from 0 to 15. Raise it when the bars come out grey, lower it when they bleed.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Print density'),
        ),
        migrations.AddField(
            model_name='rentalconfig',
            name='label_printer_dpi',
            field=models.PositiveIntegerField(choices=[(203, '203 dpi'), (300, '300 dpi')], default=203, help_text='Print head resolution, used to convert millimetres to dots.', verbose_name='Label printer resolution'),
        ),
        migrations.AddField(
            model_name='rentalconfig',
            name='label_printer_host',
            field=models.CharField(blank=True, help_text='IP address or hostname of the TSPL label printer. Leave empty to print labels through the browser only.', max_length=255, verbose_name='Label printer host'),
        ),
        migrations.AddField(
            model_name='rentalconfig',
            name='label_printer_port',
            field=models.PositiveIntegerField(default=9100, help_text='Raw socket port of the label printer, usually 9100.', verbose_name='Label printer port'),
        ),
        migrations.AddField(
            model_name='rentalconfig',
            name='label_printer_speed',
            field=models.PositiveSmallIntegerField(default=4, help_text='Printing speed in inches per second.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Print speed (inch/s)'),
        ),
    ]
