# Generated by Django 6.0.6 on 2026-09-16 12:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0024_label_printer_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalconfig',
            name='label_offset_x_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Moves the printed content to the right. Use it when the roll does not sit centred under the print head.', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('-10')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Horizontal offset (mm)'),
        ),
        migrations.AddField(
            model_name='rentalconfig',
            name='label_offset_y_mm',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Moves the printed content down, away from the top edge. The content is laid out in what is left of the label, so nothing is pushed over the bottom edge.', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('-10')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Top offset (mm)'),
        ),
    ]
