# Generated by Django 6.0.6 on 2026-09-16 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0025_label_print_offsets'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Identifies the format in the print URL. Changing it breaks links that were already handed out.', unique=True, verbose_name='Key')),
                ('name', models.CharField(help_text='Shown in the format chooser, e.g. "Roll label".', max_length=100, verbose_name='Name')),
                ('width_mm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)], verbose_name='Width (mm)')),
                ('height_mm', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(200)], verbose_name='Height (mm)')),
                ('gap_mm', models.DecimalField(blank=True, decimal_places=1, help_text='Distance to the next label on this roll. Leave empty to use the gap from the label printer settings.', max_digits=4, null=True, verbose_name='Gap (mm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Offered in the print dialog')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Label format',
                'verbose_name_plural': 'Label formats',
                'ordering': ('sort_order', 'width_mm', 'height_mm'),
            },
        ),
    ]
