# Generated by Django 6.0.6 on 2026-09-16 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0027_seed_label_formats'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lines print in this order, top to bottom.', verbose_name='Position')),
                ('content', models.CharField(choices=[('number_owner', 'Inventory number and owner'), ('number', 'Inventory number'), ('owner', 'Owner'), ('barcode', 'Barcode'), ('description', 'Description'), ('location', 'Location')], max_length=20, verbose_name='Content')),
                ('size', models.CharField(choices=[('small', 'Small'), ('normal', 'Normal'), ('large', 'Large')], default='normal', max_length=10, verbose_name='Size')),
                ('align', models.CharField(choices=[('left', 'Left'), ('center', 'Centred'), ('right', 'Right')], default='center', max_length=10, verbose_name='Alignment')),
                ('shorten_words', models.BooleanField(default=True, help_text='Abbreviates the words of a location that would not fit ("Schrank" becomes "Schr."), keeping the codes intact. Only applies to the location line.', verbose_name='Shorten words when needed')),
                ('highlight_codes', models.BooleanField(default=True, help_text='Prints the number or letter that ends a location level larger than the words around it. Turn this off where locations carry no such codes. Location line only.', verbose_name='Enlarge the codes')),
                ('drop_leading_segments', models.PositiveSmallIntegerField(default=0, help_text='Leaves out this many levels from the front of a location, for a first level everybody knows anyway.', verbose_name='Drop leading location levels')),
                ('label_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rental.labelformat', verbose_name='Label format')),
            ],
            options={
                'verbose_name': 'Label line',
                'verbose_name_plural': 'Label lines',
                'ordering': ('position', 'pk'),
            },
        ),
    ]
