# Generated by Django 5.2.5 on 2025-10-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='number',
            field=models.IntegerField(db_index=True, help_text='Identification number matching License number (multiple versions allowed)', verbose_name='Number'),
        ),
        migrations.AlterUniqueTogether(
            name='videofile',
            unique_together={('number', 'storage_location')},
        ),
    ]
