# Generated by Django 5.2.5 on 2025-10-17 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0004_add_unc_path_to_storage'),
    ]

    operations = [
        # This is a placeholder migration to maintain migration chain consistency.
        # No actual database changes are performed here.
    ]
