# Generated by Django 5.2.7 on 2025-10-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0005_systemmanagementproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemManagementProxy',
            fields=[
            ],
            options={
                'verbose_name': '🎛️ System Management',
                'verbose_name_plural': '🎛️ System Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('media_files.videofile',),
        ),
        # Remove unique constraint on number and storage_location if it exists
        # This is a safer approach than using AlterUniqueTogether which expects the constraint to exist
        migrations.RunSQL(
            "ALTER TABLE media_files_videofile DROP CONSTRAINT IF EXISTS media_files_videofile_number_storage_location_id_8c9f8f3a_uniq;",
            reverse_sql="ALTER TABLE media_files_videofile ADD CONSTRAINT media_files_videofile_number_storage_location_id_8c9f8f3a_uniq UNIQUE (number, storage_location_id);",
            elidable=True
        ),
        # Skip the AlterField operation since the unique constraint already exists
        # and attempting to recreate it causes an error
        migrations.RunSQL(
            # No operation needed, just a placeholder to avoid issues
            "SELECT 1;",
            reverse_sql="SELECT 1;",
            elidable=True
        ),
    ]
