# Generated by Django 5.2.7 on 2025-11-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0007_restore_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='number',
            field=models.IntegerField(db_index=True, help_text='Identification number matching License number (unique per storage location)', verbose_name='Number'),
        ),
    ]

