# Generated by Django 5.2.7 on 2025-12-25 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0009_alter_videofile_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlay_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=20, verbose_name='Type')),
                ('segment', models.CharField(choices=[('intro', 'Intro'), ('outro', 'Outro')], default='intro', help_text='Apply this overlay to intro or outro segment', max_length=10, verbose_name='Segment')),
                ('order', models.IntegerField(default=0, help_text='Rendering order (lower number = rendered first/bottom layer)', verbose_name='Order')),
                ('text_template', models.TextField(blank=True, help_text='Template with variables like {license.title}, {profile.display}', verbose_name='Text Template')),
                ('image_path', models.CharField(blank=True, help_text='Path to image file (relative to assets/ or absolute)', max_length=500, verbose_name='Image Path')),
                ('image_width', models.IntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('image_height', models.IntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('position_preset', models.CharField(choices=[('custom', 'Custom'), ('center', 'Center'), ('top_left', 'Top Left'), ('top_center', 'Top Center'), ('top_right', 'Top Right'), ('bottom_left', 'Bottom Left'), ('bottom_center', 'Bottom Center'), ('bottom_right', 'Bottom Right'), ('lower_third_left', 'Lower Third Left'), ('lower_third_right', 'Lower Third Right')], default='custom', max_length=30, verbose_name='Position Preset')),
                ('x_position', models.CharField(default='(w-text_w)/2', help_text='X coordinate or expression (e.g., "(w-text_w)/2", "40")', max_length=100, verbose_name='X Position')),
                ('y_position', models.CharField(default='(h-text_h)/2', help_text='Y coordinate or expression (e.g., "h-140", "(h-text_h)/2")', max_length=100, verbose_name='Y Position')),
                ('start_time', models.FloatField(default=0.0, help_text='When to show this overlay (relative to segment start)', verbose_name='Start Time (seconds)')),
                ('end_time', models.FloatField(default=5.0, help_text='When to hide this overlay (relative to segment start)', verbose_name='End Time (seconds)')),
                ('animation', models.CharField(choices=[('none', 'None'), ('fade', 'Fade'), ('slide_up', 'Slide Up'), ('slide_left', 'Slide Left'), ('slide_right', 'Slide Right'), ('slide_down', 'Slide Down')], default='fade', max_length=20, verbose_name='Animation')),
                ('fade_in_duration', models.FloatField(default=0.4, verbose_name='Fade In Duration (seconds)')),
                ('fade_out_duration', models.FloatField(default=0.4, verbose_name='Fade Out Duration (seconds)')),
                ('font_file', models.CharField(default='fonts/Roboto-Regular.ttf', help_text='Path relative to assets/ (e.g., "fonts/Roboto-Bold.ttf")', max_length=500, verbose_name='Font File')),
                ('font_size', models.IntegerField(default=48, verbose_name='Font Size')),
                ('font_color', models.CharField(default='white', help_text='Color name or hex (e.g., "white", "#FFFFFF")', max_length=50, verbose_name='Font Color')),
                ('has_box', models.BooleanField(default=False, verbose_name='Has Background Box')),
                ('box_color', models.CharField(default='black@0.5', help_text='Color with opacity (e.g., "black@0.5")', max_length=50, verbose_name='Box Color')),
                ('box_border_width', models.IntegerField(default=12, verbose_name='Box Border Width')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Preset Overlay',
                'verbose_name_plural': 'Preset Overlays',
                'ordering': ['preset', 'segment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VideoPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this preset (e.g., "my_custom_lower_third")', max_length=255, unique=True, verbose_name='Preset Name')),
                ('display_name', models.CharField(help_text='Human-readable name shown in UI', max_length=255, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of this preset', verbose_name='Description')),
                ('is_template', models.BooleanField(default=False, help_text='If true, this preset serves as a starting template for new presets', verbose_name='Is Template')),
                ('segment_duration', models.FloatField(default=5.0, help_text='Duration for intro/outro overlay segments', verbose_name='Segment Duration (seconds)')),
                ('intro_clip_path', models.CharField(blank=True, help_text='Optional path to intro video clip', max_length=500, verbose_name='Intro Clip Path')),
                ('outro_clip_path', models.CharField(blank=True, help_text='Optional path to outro video clip', max_length=500, verbose_name='Outro Clip Path')),
                ('is_public', models.BooleanField(default=False, help_text='If true, this preset is available to all users', verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Preset',
                'verbose_name_plural': 'Video Presets',
                'ordering': ['display_name'],
            },
        ),
        migrations.RenameIndex(
            model_name='videofile',
            new_name='media_files_number_4843df_idx',
            old_name='media_files_number_storage_idx',
        ),
        migrations.AlterField(
            model_name='fileoperation',
            name='operation_type',
            field=models.CharField(choices=[('SCAN', 'Scan'), ('COPY', 'Copy'), ('MOVE', 'Move'), ('DELETE', 'Delete'), ('METADATA_UPDATE', 'Metadata Update'), ('VERIFY', 'Verify Integrity'), ('RENDER', 'Render')], max_length=20, verbose_name='Operation Type'),
        ),
        migrations.AddField(
            model_name='videopreset',
            name='based_on',
            field=models.ForeignKey(blank=True, help_text='Original preset this was copied from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_files.videopreset', verbose_name='Based On'),
        ),
        migrations.AddField(
            model_name='videopreset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_presets', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='presetoverlay',
            name='preset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlays', to='media_files.videopreset', verbose_name='Preset'),
        ),
    ]
