# Generated by Django 5.2.7 on 2025-12-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0011_videofile_is_manual_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEncodePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this encoding preset (e.g., "1080p25_9000k")', max_length=255, unique=True, verbose_name='Preset Name')),
                ('display_name', models.CharField(blank=True, help_text='Human-readable name shown in UI (auto-generated if empty)', max_length=255, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of this encoding preset', verbose_name='Description')),
                ('width', models.IntegerField(help_text='Video width in pixels', verbose_name='Width')),
                ('height', models.IntegerField(help_text='Video height in pixels', verbose_name='Height')),
                ('fps', models.IntegerField(help_text='Frames per second', verbose_name='FPS')),
                ('vcodec', models.CharField(default='libx264', help_text='Video codec (e.g., "libx264")', max_length=50, verbose_name='Video Codec')),
                ('video_bitrate_k', models.IntegerField(default=9000, help_text='Video bitrate in kilobits per second', verbose_name='Video Bitrate (kbps)')),
                ('acodec', models.CharField(default='aac', help_text='Audio codec (e.g., "aac")', max_length=50, verbose_name='Audio Codec')),
                ('audio_bitrate_k', models.IntegerField(default=192, help_text='Audio bitrate in kilobits per second', verbose_name='Audio Bitrate (kbps)')),
                ('audio_sample_rate', models.IntegerField(default=48000, help_text='Audio sample rate in Hz', verbose_name='Audio Sample Rate (Hz)')),
                ('audio_channels', models.IntegerField(default=2, help_text='Number of audio channels', verbose_name='Audio Channels')),
                ('pix_fmt', models.CharField(default='yuv420p', help_text='Pixel format (e.g., "yuv420p")', max_length=50, verbose_name='Pixel Format')),
                ('x264_preset', models.CharField(default='veryfast', help_text='x264 encoding preset (e.g., "veryfast", "medium", "slow")', max_length=50, verbose_name='x264 Preset')),
                ('x264_profile', models.CharField(default='high', help_text='x264 profile (e.g., "baseline", "main", "high")', max_length=50, verbose_name='x264 Profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Encode Preset',
                'verbose_name_plural': 'Video Encode Presets',
                'ordering': ['name'],
            },
        ),
    ]
