# Generated by Django 5.2.7 on 2025-12-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0012_videoencodepreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetoverlay',
            name='animation',
            field=models.CharField(choices=[('none', 'None'), ('fade', 'Fade'), ('slide_up', 'Slide Up'), ('slide_left', 'Slide Left'), ('slide_right', 'Slide Right'), ('slide_down', 'Slide Down'), ('zoom_in', 'Zoom In'), ('zoom_out', 'Zoom Out')], default='fade', max_length=20, verbose_name='Animation'),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
    ]
