# Generated by Django 5.2.7 on 2026-01-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0014_storagelocation_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
