# Generated by Django 5.2.7 on 2026-01-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0015_alter_videofile_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFilesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlay_rendering_enabled', models.BooleanField(default=False, help_text='Enable video overlay rendering features (text overlays)', verbose_name='Overlay Rendering Enabled')),
                ('auto_copy_on_schedule', models.BooleanField(default=False, help_text='Automatically copy videos when saving broadcast plans', verbose_name='Auto Copy on Schedule')),
                ('auto_copy_to_archive', models.BooleanField(default=False, help_text='Automatically copy videos to archive storage when planning', verbose_name='Auto Copy to Archive')),
                ('auto_copy_to_playout', models.BooleanField(default=False, help_text='Automatically copy videos to playout storage when planning', verbose_name='Auto Copy to Playout')),
                ('use_weekly_folders', models.BooleanField(default=True, help_text='Use weekly folders (YYYY_KW_WW format) in playout storage', verbose_name='Use Weekly Folders')),
                ('archive_protected', models.BooleanField(default=True, help_text='Protect ARCHIVE storage from deletion (read-only access)', verbose_name='Archive Protected')),
                ('source_preference_custom_days', models.IntegerField(default=7, help_text='Number of days to consider CUSTOM storage files as "recent"', verbose_name='Source Preference Custom Days')),
                ('default_playout_storage_name', models.CharField(blank=True, help_text='Default playout storage name (auto-detected if empty)', max_length=255, verbose_name='Default Playout Storage Name')),
                ('default_playout_storage_path', models.CharField(blank=True, help_text='Default playout storage path (auto-detected if empty)', max_length=500, verbose_name='Default Playout Storage Path')),
                ('auto_delete_from_custom', models.BooleanField(default=True, help_text='Auto-delete videos from CUSTOM storage after successful copy', verbose_name='Auto Delete from Custom')),
                ('copy_verify_checksum', models.BooleanField(default=True, help_text='Verify checksum during video copy operations (SHA256)', verbose_name='Copy Verify Checksum')),
                ('copy_use_md5_for_archive', models.BooleanField(default=True, help_text='Use faster MD5 checksum for ARCHIVE sources instead of SHA256', verbose_name='Copy Use MD5 for Archive')),
            ],
            options={
                'verbose_name': 'Media Files Configuration',
                'verbose_name_plural': 'Media Files Configuration',
            },
        ),
    ]
