# Generated by Django 5.2.7 on 2026-01-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0016_mediafilesconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafilesconfig',
            name='supported_formats',
            field=models.CharField(default='mp4,mov,mpeg,mpg', help_text='Comma-separated list of supported video file extensions (e.g., mp4,mov,mpeg,mpg)', max_length=200, verbose_name='Supported Video Formats'),
        ),
    ]
