# Generated by Cursor on 2026-01-19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0005_video_presets_from_media_files"),
        ("media_files", "0018_mediafilesconfig_hevc_transcode"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="PresetOverlay"),
                migrations.DeleteModel(name="VideoEncodePreset"),
                migrations.DeleteModel(name="VideoPreset"),
            ],
        ),
    ]

