# Generated by Django 6.0.6 on 2026-06-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0020_videofile_is_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmanagementproxy',
            options={'verbose_name': 'System Management', 'verbose_name_plural': 'System Management'},
        ),
    ]
