# Generated by Django 6.0.6 on 2026-06-26 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0024_covertemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='covertemplate',
            options={'ordering': ['priority', 'id'], 'verbose_name': 'Cover-Vorlagenregel', 'verbose_name_plural': 'Cover-Vorlagenregeln'},
        ),
        migrations.AddField(
            model_name='mediafilesconfig',
            name='cover_output_storage',
            field=models.ForeignKey(blank=True, help_text='Verbundener Speicherort, in den die Cover geschrieben werden. Bevorzugt gegenüber einem manuellen Pfad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_output_configs', to='media_files.storagelocation', verbose_name='Cover-Speicherort'),
        ),
        migrations.AddField(
            model_name='mediafilesconfig',
            name='cover_output_subdir',
            field=models.CharField(blank=True, help_text='Optionaler Unterordner innerhalb des gewählten Speicherorts (z. B. "covers").', max_length=255, verbose_name='Cover-Unterordner'),
        ),
        migrations.AlterField(
            model_name='covertemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='covertemplate',
            name='match_pattern',
            field=models.CharField(blank=True, help_text='Regulärer Ausdruck. Bei "Serie" wird gegen den Lizenztitel geprüft, bei "Kategorie" gegen den Kategorienamen. Für eine Kanal-Standardregel leer lassen.', max_length=500, verbose_name='Suchmuster'),
        ),
        migrations.AlterField(
            model_name='covertemplate',
            name='name',
            field=models.CharField(help_text='Sprechende Bezeichnung für diese Regel.', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='covertemplate',
            name='priority',
            field=models.IntegerField(default=100, help_text='Kleinere Zahlen werden zuerst ausgewertet (höhere Priorität).', verbose_name='Priorität'),
        ),
        migrations.AlterField(
            model_name='covertemplate',
            name='scope',
            field=models.CharField(choices=[('series', 'Serie (Regex auf Titel)'), ('category', 'Kategorie (Regex auf Kategoriename)'), ('channel', 'Kanal-Standard (trifft immer zu)')], default='category', max_length=20, verbose_name='Geltungsbereich'),
        ),
        migrations.AlterField(
            model_name='covertemplate',
            name='template',
            field=models.CharField(choices=[('base', 'Basis'), ('journal', 'Journal (große Folgennummer)'), ('trailer', 'Trailer (cineastisch)')], default='base', max_length=20, verbose_name='Vorlage'),
        ),
        migrations.AlterField(
            model_name='covertemplate',
            name='theme',
            field=models.JSONField(blank=True, help_text='Optionale Überschreibungen, z. B. {"accent": "#FF6B00", "background_style": "cinematic"}. background_style: bottom, bottom_left oder cinematic.', null=True, verbose_name='Theme-Überschreibungen'),
        ),
        migrations.AlterField(
            model_name='mediafilesconfig',
            name='cover_body_font_path',
            field=models.CharField(blank=True, help_text='Absoluter Pfad zu einer .ttf-Schrift für Fließtext (Autor, Untertitel). Leer lassen, um die mitgelieferte Standardschrift (Roboto-Regular) zu verwenden.', max_length=500, verbose_name='Cover-Schriftart Fließtext'),
        ),
        migrations.AlterField(
            model_name='mediafilesconfig',
            name='cover_category_colors',
            field=models.JSONField(blank=True, help_text='Optionale Zuordnung von Kategoriename zu Akzentfarbe (Hex), z. B. {"Magazin": "#E6007E"}. Nicht gelistete Kategorien verwenden eine Standardpalette.', null=True, verbose_name='Cover-Kategoriefarben'),
        ),
        migrations.AlterField(
            model_name='mediafilesconfig',
            name='cover_enabled',
            field=models.BooleanField(default=False, help_text='Erzeugt automatisch Cover-Bilder (Thumbnails) aus einem Videobild sowie Lizenz-Metadaten und Branding.', verbose_name='Cover-Generierung aktiviert'),
        ),
        migrations.AlterField(
            model_name='mediafilesconfig',
            name='cover_logo_path',
            field=models.CharField(blank=True, help_text='Absoluter Pfad zum Logo (PNG mit Transparenz), das auf die Cover gezeichnet wird. Leer lassen, um das mitgelieferte Standardlogo zu verwenden.', max_length=500, verbose_name='Cover-Logo-Pfad'),
        ),
        migrations.AlterField(
            model_name='mediafilesconfig',
            name='cover_output_dir',
            field=models.CharField(blank=True, help_text='Manueller Pfad als Alternative zum Speicherort. Wird nur verwendet, wenn kein Cover-Speicherort gewählt ist. Leer lassen, um den Thumbnail-Pfad des austausch-Exports zu verwenden.', max_length=500, verbose_name='Cover-Ausgabeverzeichnis (manuell)'),
        ),
        migrations.AlterField(
            model_name='mediafilesconfig',
            name='cover_template_rules',
            field=models.JSONField(blank=True, help_text='Optionale Zuordnung von Kategoriename zu Cover-Vorlage, z. B. {"Trailer": "trailer"}. Verfügbar: base, journal, trailer. Nicht gelistete Kategorien verwenden die Vorlage "base".', null=True, verbose_name='Cover-Vorlagenregeln'),
        ),
        migrations.AlterField(
            model_name='mediafilesconfig',
            name='cover_title_font_path',
            field=models.CharField(blank=True, help_text='Absoluter Pfad zu einer .ttf-Schrift für Überschriften. Leer lassen, um die mitgelieferte Standardschrift (Roboto-Bold) zu verwenden.', max_length=500, verbose_name='Cover-Schriftart Titel'),
        ),
    ]
