# Generated by Django 6.0.6 on 2026-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0025_alter_covertemplate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('pool', models.CharField(db_index=True, help_text='Gruppenname, z. B. "podcast". Eine Regel ordnet ein Suchmuster diesem Pool zu.', max_length=100, verbose_name='Pool')),
                ('image', models.FileField(help_text='Transparentes PNG oder SVG, 16:9 (z. B. 1280×720).', upload_to='cover_overlays/', verbose_name='Grafik (PNG/SVG)')),
                ('text_area', models.JSONField(blank=True, help_text='Optional, wo Titel/Autor gezeichnet werden, z. B. {"x": 56, "y": 470, "w": 1168, "h": 180, "align": "left", "color": "#FFFFFF"}. Leer = unten zentriert.', null=True, verbose_name='Textbereich')),
                ('accent', models.CharField(blank=True, help_text='Optionaler Hex-Wert, z. B. "#E6007E".', max_length=20, verbose_name='Akzentfarbe')),
                ('use_video_frame', models.BooleanField(default=True, help_text='Aus: Grafik auf einfarbigem Hintergrund statt auf einem Videobild (für vollflächige Designs).', verbose_name='Videobild verwenden')),
                ('darken_frame', models.BooleanField(default=True, help_text='Unteren Bildbereich abdunkeln, damit Text lesbar bleibt.', verbose_name='Videobild abdunkeln')),
                ('draw_logo', models.BooleanField(default=True, help_text='Aus, wenn die Grafik bereits ein Logo enthält.', verbose_name='Logo zeichnen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cover-Grafik',
                'verbose_name_plural': 'Cover-Grafiken',
                'ordering': ['pool', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoverOverlayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('scope', models.CharField(choices=[('series', 'Serie (Regex auf Titel)'), ('category', 'Kategorie (Regex auf Kategoriename)'), ('channel', 'Kanal-Standard (trifft immer zu)')], default='series', max_length=20, verbose_name='Geltungsbereich')),
                ('match_pattern', models.CharField(blank=True, help_text='Regulärer Ausdruck, z. B. "Podcast". Bei "Serie" gegen den Titel, bei "Kategorie" gegen den Kategorienamen.', max_length=500, verbose_name='Suchmuster')),
                ('pool', models.CharField(help_text='Welcher Cover-Grafik-Pool verwendet wird.', max_length=100, verbose_name='Pool')),
                ('selection_mode', models.CharField(choices=[('random', 'Zufällig (ein stabiler Treffer pro Nummer)'), ('all', 'Alle (Varianten + Kontaktbogen zur Auswahl)')], default='random', max_length=10, verbose_name='Auswahlmodus')),
                ('priority', models.IntegerField(default=50, help_text='Kleinere Zahlen zuerst. Grafikregeln gehen Vorlagenregeln vor.', verbose_name='Priorität')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Cover-Grafikregel',
                'verbose_name_plural': 'Cover-Grafikregeln',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
