# Generated by Django 6.0.6 on 2026-06-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0026_coveroverlay_coveroverlayrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveroverlay',
            name='logo_area',
            field=models.JSONField(blank=True, help_text='Optional, Position/Größe des Logos, z. B. {"x": 950, "y": 40, "w": 260}. Leer = oben rechts.', null=True, verbose_name='Logo-Bereich'),
        ),
        migrations.AddField(
            model_name='coveroverlayrule',
            name='overlays',
            field=models.ManyToManyField(blank=True, help_text='Konkrete Grafiken für diese Regel. Wenn gesetzt, hat dies Vorrang vor dem Pool — so kann dieselbe Grafik in mehreren Regeln vorkommen (z. B. 1, 3, 5 für Podcasts; 2, 3 für Familie).', related_name='rules', to='media_files.coveroverlay', verbose_name='Grafiken (konkret)'),
        ),
        migrations.AlterField(
            model_name='coveroverlayrule',
            name='pool',
            field=models.CharField(blank=True, help_text='Cover-Grafik-Pool (Gruppenname). Wird verwendet, wenn unten keine konkreten Grafiken ausgewählt sind.', max_length=100, verbose_name='Pool'),
        ),
    ]
