# Generated by Django 6.0.6 on 2026-06-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0027_coveroverlay_logo_area_coveroverlayrule_overlays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafilesconfig',
            name='cover_logo',
            field=models.ImageField(blank=True, help_text='Logo (PNG mit Transparenz), das auf die Cover gezeichnet wird — hier direkt hochladen. Leer lassen, um das mitgelieferte Standardlogo zu verwenden.', null=True, upload_to='cover_branding/', verbose_name='Cover-Logo'),
        ),
        migrations.AlterField(
            model_name='mediafilesconfig',
            name='cover_logo_path',
            field=models.CharField(blank=True, help_text='Optionaler absoluter Server-Pfad als Alternative zum Upload. Wird nur verwendet, wenn oben kein Logo hochgeladen ist.', max_length=500, verbose_name='Cover-Logo-Pfad (manuell)'),
        ),
    ]
