# Generated by Django 6.0.6 on 2026-07-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0029_coveroverlay_draw_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafilesconfig',
            name='render_encode_preset',
            field=models.CharField(blank=True, default='1080p25_9000k', help_text='Encoding preset used by the "Render video" admin actions (e.g., "1080p25_9000k"). The bitrate comes from the selected preset (tools.VideoEncodePreset or JSON).', max_length=100, verbose_name='Render Encoding Preset'),
        ),
    ]
