from . import api
from . import views
from django.urls import path


app_name = 'licenses'
urlpatterns = [
    path(
        '',
        views.ListLicensesView.as_view(),
        name='licenses',
    ),
    path(
        'create/',
        views.CreateLicenseView.as_view(),
        name='create',
    ),
    path(
        '<int:pk>/',
        views.DetailsLicensesView.as_view(),
        name='details',
    ),
    path(
        '<int:pk>/update/',
        views.UpdateLicensesView.as_view(),
        name='update',
    ),
    path(
        '<int:pk>/filled_license_file/',
        views.FilledLicenseFile.as_view(),
        name='print'
    ),
    path(
        'api/metadata/<int:number>/',
        api.LicenseMetadataView.as_view(),
        name='api-metadata'
    ),
    path(
        '<int:pk>/delete/',
        views.DeleteLicenseView.as_view(),
        name='delete'
    ),
    path(
        '<int:pk>/copy/',
        views.CopyLicenseView.as_view(),
        name='copy'
    ),
    path(
        '<int:pk>/get-upload-token/',
        views.GetUploadTokenView.as_view(),
        name='get_upload_token'
    ),
    path(
        '<int:pk>/confirm-upload/',
        views.ConfirmUploadView.as_view(),
        name='confirm_upload'
    ),
    path(
        '<int:pk>/save-signature/',
        views.SaveSignatureView.as_view(),
        name='save_signature'
    ),
    path(
        '<int:pk>/sign-session/create/',
        views.CreateSigningSessionView.as_view(),
        name='create_sign_session'
    ),
    path(
        'sign-session/create/',
        views.CreatePreLicenseSigningSessionView.as_view(),
        name='create_prelicense_sign_session'
    ),
    path(
        'sign-session/<str:token>/status/',
        views.SigningSessionStatusView.as_view(),
        name='sign_session_status'
    ),
    path(
        'sign-session/<str:token>/qr/',
        views.SigningSessionQRCodeView.as_view(),
        name='sign_session_qr'
    ),
    path(
        'sign-session/<str:token>/',
        views.SigningSessionPageView.as_view(),
        name='sign_session_page'
    ),
    path(
        'sign-session/<str:token>/submit/',
        views.SubmitSigningSessionView.as_view(),
        name='sign_session_submit'
    ),
]
