# Generated by Django 5.2.5 on 2025-08-31 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Dashboard Cache',
                'verbose_name_plural': 'Dashboard Caches',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_contributions', models.IntegerField(default=0)),
                ('primary_contributions', models.IntegerField(default=0)),
                ('live_contributions', models.IntegerField(default=0)),
                ('contributions_by_media_authority', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Contribution Statistics',
                'verbose_name_plural': 'Contribution Statistics',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='LicenseStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_licenses', models.IntegerField(default=0)),
                ('confirmed_licenses', models.IntegerField(default=0)),
                ('new_licenses', models.IntegerField(default=0)),
                ('licenses_by_category', models.JSONField(default=dict)),
                ('licenses_by_media_authority', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'License Statistics',
                'verbose_name_plural': 'License Statistics',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_users', models.IntegerField(default=0)),
                ('male_users', models.IntegerField(default=0)),
                ('female_users', models.IntegerField(default=0)),
                ('diverse_users', models.IntegerField(default=0)),
                ('verified_users', models.IntegerField(default=0)),
                ('member_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User Statistics',
                'verbose_name_plural': 'User Statistics',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
