# Generated by Django 5.2.5 on 2025-09-06 00:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_initial'),
        ('dashboard', '0001_initial'),
        ('licenses', '0004_license_infoblock'),
        ('rental', '0008_past_time_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='Triggered At')),
                ('current_value', models.FloatField(verbose_name='Current Value')),
                ('threshold_value', models.FloatField(verbose_name='Threshold Value')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Is Resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
            ],
            options={
                'verbose_name': 'Alert Log',
                'verbose_name_plural': 'Alert Logs',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Alert Name')),
                ('metric_type', models.CharField(choices=[('conversion_rate', 'Conversion Rate'), ('absolute_count', 'Absolute Count'), ('trend_change', 'Trend Change')], max_length=50, verbose_name='Metric Type')),
                ('stage', models.CharField(choices=[('registered', 'Registered'), ('verified', 'Verified'), ('rental_requested', 'Rental Requested'), ('rental_completed', 'Rental Completed'), ('license_created', 'License Created'), ('contribution_created', 'Contribution Created'), ('first_broadcast', 'First Broadcast'), ('multiple_broadcasts', 'Multiple Broadcasts')], max_length=30, verbose_name='Stage')),
                ('threshold_value', models.FloatField(verbose_name='Threshold Value')),
                ('comparison_operator', models.CharField(choices=[('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('eq', 'Equal')], max_length=10, verbose_name='Comparison Operator')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notification_recipients', models.JSONField(default=list, verbose_name='Notification Recipients')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Alert Threshold',
                'verbose_name_plural': 'Alert Thresholds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FunnelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('total_registrations', models.PositiveIntegerField(default=0, verbose_name='Total Registrations')),
                ('verified_users', models.PositiveIntegerField(default=0, verbose_name='Verified Users')),
                ('rental_requests', models.PositiveIntegerField(default=0, verbose_name='Rental Requests')),
                ('completed_rentals', models.PositiveIntegerField(default=0, verbose_name='Completed Rentals')),
                ('licenses_created', models.PositiveIntegerField(default=0, verbose_name='Licenses Created')),
                ('contributions_created', models.PositiveIntegerField(default=0, verbose_name='Contributions Created')),
                ('first_broadcasts', models.PositiveIntegerField(default=0, verbose_name='First Broadcasts')),
                ('multiple_broadcasts', models.PositiveIntegerField(default=0, verbose_name='Multiple Broadcasts')),
                ('verification_rate', models.FloatField(default=0.0, verbose_name='Verification Rate (%)')),
                ('rental_request_rate', models.FloatField(default=0.0, verbose_name='Rental Request Rate (%)')),
                ('rental_completion_rate', models.FloatField(default=0.0, verbose_name='Rental Completion Rate (%)')),
                ('license_creation_rate', models.FloatField(default=0.0, verbose_name='License Creation Rate (%)')),
                ('contribution_creation_rate', models.FloatField(default=0.0, verbose_name='Contribution Creation Rate (%)')),
                ('first_broadcast_rate', models.FloatField(default=0.0, verbose_name='First Broadcast Rate (%)')),
                ('multiple_broadcast_rate', models.FloatField(default=0.0, verbose_name='Multiple Broadcast Rate (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Funnel Metrics',
                'verbose_name_plural': 'Funnel Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('registered', 'Registered'), ('verified', 'Verified'), ('rental_requested', 'Rental Requested'), ('rental_completed', 'Rental Completed'), ('license_created', 'License Created'), ('contribution_created', 'Contribution Created'), ('first_broadcast', 'First Broadcast'), ('multiple_broadcasts', 'Multiple Broadcasts')], max_length=30, verbose_name='Stage')),
                ('achieved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Achieved At')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributions.contribution', verbose_name='Contribution')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licenses.license', verbose_name='License')),
                ('rental_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.rentalrequest', verbose_name='Rental Request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_stages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Journey Stage',
                'verbose_name_plural': 'User Journey Stages',
                'ordering': ['user', 'achieved_at'],
                'unique_together': {('user', 'stage')},
            },
        ),
        migrations.DeleteModel(
            name='ContributionStatistics',
        ),
        migrations.DeleteModel(
            name='DashboardCache',
        ),
        migrations.DeleteModel(
            name='LicenseStatistics',
        ),
        migrations.DeleteModel(
            name='UserStatistics',
        ),
        migrations.AddField(
            model_name='alertlog',
            name='threshold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.alertthreshold', verbose_name='Threshold'),
        ),
    ]
