# Generated by Django 5.1.5 on 2025-02-12 16:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial Number'),
        ),
    ]
