# Generated by Django 5.1.5 on 2025-02-17 10:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='available_for_rent',
            field=models.BooleanField(default=True, help_text='Check if this item is available for rental.', verbose_name='Available for Rental'),
        ),
    ]
