# Generated by Django 5.1.5 on 2025-02-17 11:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_available_for_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Reserved Quantity'),
        ),
    ]
