# Generated by Django 5.1.5 on 2025-02-17 14:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_reserved_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='rented_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Rented Quantity'),
        ),
    ]
