# Generated by Django 4.1.7 on 2025-05-04 21:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_rented_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_inspection',
            field=models.CharField(blank=True, choices=[('keine Prüfung', 'keine Prüfung'), (None, 'E-Inspection (format: XXXXXX)')], help_text="Enter the number in the format XXXXXX or select 'no inspection'", max_length=20, null=True, verbose_name='E-Inspection'),
        ),
    ]
