# Generated by Django 4.1.7 on 2025-05-04 22:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryitem_last_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_number_owner',
            field=models.CharField(blank=True, help_text='Enter the inventory number of the owner of the item.', max_length=255, null=True, verbose_name='Inventory Number Owner'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_inspection',
            field=models.CharField(blank=True, help_text="Enter the number in the format XXXXXX or select 'no inspection'", max_length=255, null=True, verbose_name='E-Inspection'),
        ),
    ]
