# Generated by Django 4.1.7 on 2025-05-04 22:48

from django.db import migrations
from django.db import models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryitem_inventory_number_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryimport',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed Date'),
        ),
        migrations.AddField(
            model_name='inventoryimport',
            name='error_log',
            field=models.TextField(blank=True, null=True, verbose_name='Error Log'),
        ),
        migrations.AddField(
            model_name='inventoryimport',
            name='import_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Import Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryimport',
            name='import_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], default='pending', max_length=50, verbose_name='Import Status'),
        ),
        migrations.AddField(
            model_name='inventoryimport',
            name='items_created',
            field=models.PositiveIntegerField(default=0, verbose_name='Items Created'),
        ),
        migrations.AddField(
            model_name='inventoryimport',
            name='items_skipped',
            field=models.PositiveIntegerField(default=0, verbose_name='Items Skipped'),
        ),
    ]
