# Generated by Django 4.1.7 on 2025-05-05 20:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auditlog_user_alter_auditlog_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryimport',
            name='error_log_file',
            field=models.FileField(blank=True, null=True, upload_to='error_logs/', verbose_name='Error Log File'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='available_for_rent',
            field=models.BooleanField(default=False, help_text='Check if this item is available for rental.', verbose_name='Available for Rental'),
        ),
    ]
