# Generated by Django 4.1.7 on 2025-05-05 20:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventoryimport_error_log_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryimport',
            name='error_log_file',
            field=models.FileField(blank=True, null=True, upload_to='error_logs/%Y/%m/%d/', verbose_name='Error Log File'),
        ),
    ]
