# Generated by Django 4.1.7 on 2025-05-06 22:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventoryimport_error_log_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='last_inspection',
            field=models.CharField(blank=True, help_text='Enter the number in the format XXXXXX', max_length=255, null=True, verbose_name='E-Inspection'),
        ),
    ]
