# Generated by Django 5.2 on 2025-05-16 19:34

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_alter_inventoryitem_last_inspection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="owner_inventory_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Owner Inventory Number",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
    ]
