# Generated by Django 4.1.7 on 2025-05-16 20:27

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventoryitem_owner_inventory_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.organization', verbose_name='Owner'),
        ),
    ]
