# Generated by Django 4.1.7 on 2025-05-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_inventoryitem_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='owner_inventory_number',
        ),
    ]
