# Generated by Django 5.2 on 2025-05-19 19:18

from django.db import migrations
from django.db import models
import django.core.files.storage
import django.core.validators
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_remove_inventoryitem_owner_inventory_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryimport",
            name="file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/var/folders/5l/jgq9p92150lcpcrv3pzj_csm0000gp/T/inventory_import"
                ),
                upload_to=inventory.models.InventoryImport.timestamp_path,
                validators=[
                    django.core.validators.FileExtensionValidator(["xlsx", "csv"])
                ],
                verbose_name="Inventory file",
            ),
        ),
    ]
