# Generated by Django 4.1.7 on 2025-05-19 20:09

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_inventoryimport_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_number', models.CharField(help_text='Number assigned by the inspection company', max_length=255, unique=True, verbose_name='Inspection Number')),
                ('device_name', models.CharField(blank=True, max_length=255, verbose_name='Gerät')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Hersteller')),
                ('device_type', models.CharField(blank=True, max_length=255, verbose_name='Gerätetyp')),
                ('room', models.CharField(blank=True, max_length=255, verbose_name='Raum')),
                ('target_part', models.CharField(choices=[('device', 'Whole device'), ('cable', 'Power cable'), ('psu', 'Power supply unit')], default='device', max_length=20, verbose_name='Target Part')),
                ('inspection_date', models.DateField(verbose_name='Inspection Date')),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Result / Comment')),
                ('inventory_item', models.ForeignKey(blank=True, db_column='inventory_number', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='inventory.inventoryitem', to_field='inventory_number', verbose_name='Inventory Item')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
