# Generated by Django 4.1.7 on 2025-05-19 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_inspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_inspection',
        ),
    ]
