# Generated by Django 4.1.7 on 2025-05-19 21:02

from django.db import migrations
from django.db import models
import django.core.files.storage
import django.core.validators
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_inventoryitem_last_inspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/inventory_import'), upload_to=inventory.models.InspectionImport.timestamp_path, validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='Inspection file')),
                ('import_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], default='pending', max_length=50, verbose_name='Import Status')),
                ('imported', models.BooleanField(default=False, help_text='Just marking the file as imported does not import the file!', verbose_name='Imported')),
                ('items_created', models.PositiveIntegerField(default=0, verbose_name='Items Created')),
                ('items_skipped', models.PositiveIntegerField(default=0, verbose_name='Items Skipped')),
                ('error_log', models.TextField(blank=True, null=True, verbose_name='Error Log')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name='Import Date')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Completed Date')),
                ('error_log_file', models.FileField(blank=True, null=True, upload_to='error_logs/%Y/%m/%d/', verbose_name='Error Log File')),
            ],
            options={
                'verbose_name': 'Inspection Import',
                'verbose_name_plural': 'Inspection Imports',
            },
        ),
    ]
