# Generated by Django 4.1.7 on 2025-05-19 21:32

from django.db import migrations
from django.db import models
import django.core.files.storage
import django.core.validators
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_inspectionimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionimport',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/inventory_import'), upload_to=inventory.models.InspectionImport.timestamp_path, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'csv'])], verbose_name='Inspection file'),
        ),
    ]
