# Generated by Django 4.1.7 on 2025-05-19 22:21

from django.db import migrations
from django.db import models
import django.core.validators
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_inspectionimport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='device_type',
            field=models.CharField(blank=True, max_length=255, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='room',
            field=models.CharField(blank=True, max_length=255, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='inventoryimport',
            name='file',
            field=models.FileField(upload_to=inventory.models.InventoryImport.timestamp_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'csv'])], verbose_name='Inventory file'),
        ),
    ]
