# Generated by Django 4.1.7 on 2025-05-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_inspection_device_name_and_more'),
    ]

    operations = [
    ]
