# Generated by Django 4.1.7 on 2025-05-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_populate_target_part'),
        ('inventory', '0025_populate_target_part'),
    ]

    operations = [
    ]
