# Generated by Django 4.1.7 on 2025-05-21 20:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_merge_20250521_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='target_part',
            field=models.CharField(blank=True, max_length=255, verbose_name='Target Part'),
        ),
    ]
