# Generated by Django 4.1.7 on 2025-05-21 20:57

from django.db import migrations


def forwards_func(apps, schema_editor):
    Inspection = apps.get_model('inventory', 'Inspection')
    for inspection in Inspection.objects.all():
        inspection.target_part = inspection.device_name
        inspection.save(update_fields=['target_part'])

def backwards_func(apps, schema_editor):
    # При откате можно либо очистить target_part, либо ничего не делать.
    # Оставим target_part как есть, чтобы не потерять данные, если они важны.
    # Inspection = apps.get_model('inventory', 'Inspection')
    # for inspection in Inspection.objects.all():
    #     inspection.target_part = None # или значение по умолчанию, если бы оно было
    #     inspection.save(update_fields=['target_part'])
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_change_target_part_to_charfield'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
