# Generated by Django 4.1.7 on 2025-05-21 20:57

from django.db import migrations


def forwards_func(apps, schema_editor):
    Inspection = apps.get_model('inventory', 'Inspection')
    for inspection in Inspection.objects.all():
        inspection.target_part = inspection.device_name
        inspection.save(update_fields=['target_part'])

def backwards_func(apps, schema_editor):
    # On rollback, you can either clear target_part or do nothing.
    # Leave target_part as is to avoid losing data if it's important.
    # Inspection = apps.get_model('inventory', 'Inspection')
    # for inspection in Inspection.objects.all():
    #     inspection.target_part = None # or default value if there was one
    #     inspection.save(update_fields=['target_part'])
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_change_target_part_to_charfield'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
