# Generated by Django 4.1.7 on 2025-05-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_copy_device_name_to_target_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='device_name',
        ),
    ]
