# Generated by Django 4.1.7 on 2025-08-11 20:24

from django.db import migrations
from django.db import models
import django.core.files.storage
import django.core.validators
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_location_model_and_migrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='target_part',
            field=models.CharField(choices=[('device', 'Whole device'), ('cable', 'Power cable'), ('psu', 'Power supply unit')], default='device', max_length=50, verbose_name='Target Part'),
        ),
        migrations.AlterField(
            model_name='inventoryimport',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/inventory_import'), upload_to=inventory.models.InventoryImport.timestamp_path, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'csv'])], verbose_name='Inventory file'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
