# Generated by Django 4.1.7 on 2025-08-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_category_inventoryitem_category'),
        ('inventory', '0033_merge_20250815_1040'),
    ]

    operations = [
    ]
