# Generated by Django 5.2.7 on 2026-04-26 22:37

import django.core.files.storage
import django.core.validators
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_add_celery_fields_to_inventoryimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionimport',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/var/folders/5l/jgq9p92150lcpcrv3pzj_csm0000gp/T/inventory_import'), upload_to=inventory.models.InspectionImport.timestamp_path, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'csv'])], verbose_name='Inspection file'),
        ),
        migrations.AlterField(
            model_name='inventoryimport',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/var/folders/5l/jgq9p92150lcpcrv3pzj_csm0000gp/T/inventory_import'), upload_to=inventory.models.InventoryImport.timestamp_path, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'csv'])], verbose_name='Inventory file'),
        ),
    ]
