# Generated by Django 6.0.6 on 2026-07-06 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_alter_inspectionimport_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryImageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable scanning and display of inventory item photos.', verbose_name='Enabled')),
                ('media_storage_location_id', models.PositiveIntegerField(blank=True, help_text='Use an existing storage location from the Media Files module. Takes precedence over the manual path below.', null=True, verbose_name='Media Files storage location')),
                ('base_path', models.CharField(blank=True, help_text='Absolute path to the mounted folder that holds one sub-folder per inventory number (e.g. /mnt/inventory_photos/).', max_length=500, verbose_name='Photos folder')),
                ('supported_formats', models.CharField(default='jpg,jpeg,png,gif,webp,bmp', help_text='Comma-separated list of image file extensions to scan.', max_length=200, verbose_name='Supported image formats')),
            ],
            options={
                'verbose_name': 'Inventory Photo Settings',
                'verbose_name_plural': 'Inventory Photo Settings',
            },
        ),
        migrations.CreateModel(
            name='InventoryItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500, verbose_name='Filename')),
                ('relative_path', models.CharField(help_text='Path relative to the configured photos folder.', max_length=1000, verbose_name='Relative Path')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the file is physically present on disk.', verbose_name='Available')),
                ('last_scanned', models.DateTimeField(blank=True, null=True, verbose_name='Last Scanned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.inventoryitem', verbose_name='Inventory Item')),
            ],
            options={
                'verbose_name': 'Inventory Item Photo',
                'verbose_name_plural': 'Inventory Item Photos',
                'ordering': ['filename'],
                'unique_together': {('item', 'relative_path')},
            },
        ),
    ]
