# Generated by Django 6.0.6 on 2026-07-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_inventory_item_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryimageconfig',
            name='thumbnails_beside_originals',
            field=models.BooleanField(default=False, help_text='Store generated thumbnails in a ".thumbnails" sub-folder next to the photos (requires a writable folder). When disabled, they are cached under MEDIA_ROOT. Falls back to MEDIA_ROOT if the folder is not writable.', verbose_name='Store thumbnails next to originals'),
        ),
    ]
