# Generated by Django 6.0.6 on 2026-07-06 19:08

import django.core.validators
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_inventoryimageconfig_thumbnails_beside_originals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionimport',
            name='file',
            field=models.FileField(storage=inventory.models.tmp_import_storage, upload_to=inventory.models.InspectionImport.timestamp_path, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'csv'])], verbose_name='Inspection file'),
        ),
        migrations.AlterField(
            model_name='inventoryimport',
            name='file',
            field=models.FileField(storage=inventory.models.tmp_import_storage, upload_to=inventory.models.InventoryImport.timestamp_path, validators=[django.core.validators.FileExtensionValidator(['xlsx', 'csv'])], verbose_name='Inventory file'),
        ),
    ]
