# Generated by Django 6.0.6 on 2026-07-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_alter_inspectionimport_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(help_text='Leading part of the inventory number, including the separator (e.g. "OK-").', max_length=50, unique=True, verbose_name='Prefix')),
                ('description', models.CharField(help_text='What this series stands for, e.g. "Equipment owned by the OK".', max_length=255, verbose_name='Meaning')),
                ('padding', models.PositiveSmallIntegerField(default=6, help_text='Digits the running number is padded to (6 gives OK-000001).', verbose_name='Number width')),
                ('active', models.BooleanField(default=True, help_text='Inactive series are rejected on import and are not used to generate new numbers.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Inventory Number Series',
                'verbose_name_plural': 'Inventory Number Series',
                'ordering': ['prefix'],
            },
        ),
    ]
