# Generated by Django 6.0.6 on 2026-07-15 20:00

from django.db import migrations


# Seeded so that import validation keeps behaving exactly as it did before this
# registry existed: the number format used to be hard-coded to ^OK-\d+, so "OK-"
# must be present and active from the start. An empty registry would reject
# every number on import.
DEFAULT_SERIES = [
    {
        'prefix': 'OK-',
        'description': 'Offener Kanal equipment (default series)',
        'padding': 6,
        'active': True,
    },
]


def seed_series(apps, schema_editor):
    """Create the default inventory number series."""
    InventorySeries = apps.get_model('inventory', 'InventorySeries')
    for series in DEFAULT_SERIES:
        InventorySeries.objects.get_or_create(
            prefix=series['prefix'],
            defaults={
                'description': series['description'],
                'padding': series['padding'],
                'active': series['active'],
            },
        )


def unseed_series(apps, schema_editor):
    """Remove the default inventory number series."""
    InventorySeries = apps.get_model('inventory', 'InventorySeries')
    InventorySeries.objects.filter(
        prefix__in=[s['prefix'] for s in DEFAULT_SERIES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_inventoryseries'),
    ]

    operations = [
        migrations.RunPython(seed_series, unseed_series),
    ]
