# Generated by Django 6.0.6 on 2026-07-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_seed_inventory_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Free text about this item, e.g. defects or accessories.', null=True, verbose_name='Notes'),
        ),
    ]
