# Generated by Django 5.2.5 on 2025-08-25 18:08

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the notification', max_length=200, verbose_name='Title')),
                ('message', models.TextField(help_text='Main notification text', verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', help_text='Notification type determines color and style', max_length=10, verbose_name='Type')),
                ('icon', models.CharField(choices=[('info-circle', 'Info Circle'), ('check-circle', 'Check Circle'), ('exclamation-triangle', 'Exclamation Triangle'), ('exclamation-circle', 'Exclamation Circle'), ('clock', 'Clock'), ('bell', 'Bell'), ('broadcast', 'Broadcast'), ('star', 'Star'), ('gear', 'Gear'), ('shield-check', 'Shield Check')], default='info-circle', help_text='Bootstrap Icons icon name', max_length=20, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, help_text='Only active notifications are displayed to users', verbose_name='Active')),
                ('priority', models.IntegerField(default=1, help_text='Higher priority notifications appear first (1-10)', verbose_name='Priority')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When to start showing this notification', verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing this notification (optional)', null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
