# Generated by Django 4.0.5 on 2022-07-26 09:01

from django.db import migrations
from django.db import models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='media_autority',
            field=models.ForeignKey(default=registration.models.default_media_authority,
                                    on_delete=django.db.models.deletion.CASCADE, to='registration.mediaauthority'),
        ),
    ]
