# Generated by Django 4.0.5 on 2022-08-29 12:47

from django.db import migrations
from django.db import models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(
                2022, 8, 29, 14, 47, 15, 121757)),
        ),
    ]
