# Generated by Django 4.0.5 on 2022-09-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='media_autority',
            new_name='media_authority',
        ),
    ]
