# Generated by Django 4.1.3 on 2022-12-19 10:22

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(
                max_length=35, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('none', 'not given'), ('m', 'male'), ('f', 'female'), (
                'd', 'diverse')], default='none', max_length=4, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='media_authority',
            field=models.ForeignKey(default=registration.models.default_media_authority,
                                    on_delete=django.db.models.deletion.CASCADE, to='registration.mediaauthority', verbose_name='Media Authority'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='okuser',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(
                max_length=5, null=True, verbose_name='zipcode'),
        ),
    ]
