# Generated by Django 4.0.5 on 2022-09-15 06:29

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_media_autority_profile_media_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member',
            field=models.BooleanField(default=False, verbose_name='member'),
        ),
    ]
