# Generated by Django 5.2.5 on 2025-10-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_notification_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ausweisnummer',
            field=models.CharField(blank=True, help_text='ID document number (passport, ID card, etc.)', max_length=50, null=True, verbose_name='ID document number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_data_sharing_allowed',
            field=models.BooleanField(default=False, help_text='Permission to share email address with third parties', verbose_name='Email data sharing allowed'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_data_sharing_allowed',
            field=models.BooleanField(default=False, help_text='Permission to share phone number with third parties', verbose_name='Phone data sharing allowed'),
        ),
        migrations.AlterField(
            model_name='mediaauthority',
            name='name',
            field=models.CharField(default='OK Bayern', max_length=150, unique=True, verbose_name='Media Authority'),
        ),
    ]
