# Generated by Django 4.1.3 on 2022-12-20 12:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_profile_city_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='comment'),
        ),
    ]
