# Generated by Django 4.0.5 on 2022-07-06 13:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_profile_house_number_alter_profile_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(
                default=False, help_text='The profile data was verified by showing the ID to an employee.'),
        ),
    ]
