# Generated by Django 5.2.5 on 2025-10-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_profile_ausweisnummer_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['first_name', 'last_name'], name='profile_name_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['ausweisnummer'], name='profile_ausweis_idx'),
        ),
    ]
