# Generated by Django 4.0.5 on 2022-09-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaauthority',
            options={'verbose_name': 'Media Authority',
                     'verbose_name_plural': 'Media Authorities'},
        ),
        migrations.AlterModelOptions(
            name='okuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile',
                     'verbose_name_plural': 'Profiles'},
        ),
    ]
