# Generated by Django 4.0.5 on 2022-08-29 14:18

from django.db import migrations
from django.db import models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_profile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=registration.models.now),
        ),
    ]
