# Generated by Django 5.2.5 on 2025-10-23 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_add_profile_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaauthority',
            name='name',
            field=models.CharField(default='OK Merseburg', max_length=150, unique=True, verbose_name='Media Authority'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
        ),
    ]
