# Generated by Django 4.0.5 on 2022-07-11 15:22

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_profile_okuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='okuser',
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
