# Generated by Django 5.2.7 on 2025-11-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_no_model_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaauthority',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the media authority (e.g., "Offener Kanal Dessau")', max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='global_producer',
            field=models.BooleanField(default=False, help_text='Global producer status for the profile.', verbose_name='Global Producer'),
        ),
        migrations.AlterField(
            model_name='mediaauthority',
            name='name',
            field=models.CharField(default='OKMQ', max_length=150, unique=True, verbose_name='Media Authority'),
        ),
    ]
