# Generated by Django 5.2.7 on 2025-11-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_add_full_name_to_media_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaauthority',
            name='name',
            field=models.CharField(default='OKMQ', max_length=150, unique=True, verbose_name='Media Authority'),
        ),
    ]

