# Generated by Django 5.2.7 on 2026-01-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_add_target_channel_to_media_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_pdf', models.CharField(default='Nutzerkartei_Anmeldung_2022_n.pdf', help_text='PDF template file for registration form (must be in files/ directory)', max_length=255, verbose_name='Registration Form PDF')),
                ('form_type', models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML'), ('TEXT', 'TEXT')], default='PDF', help_text='Type of registration form to generate', max_length=10, verbose_name='Registration Form Type')),
            ],
            options={
                'verbose_name': 'Registration Configuration',
                'verbose_name_plural': 'Registration Configuration',
            },
        ),
        migrations.AlterField(
            model_name='mediaauthority',
            name='name',
            field=models.CharField(default='OKMQ CMO', max_length=150, unique=True, verbose_name='Media Authority'),
        ),
    ]
