# Generated by Django 5.2.7 on 2026-01-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_registrationconfig_alter_mediaauthority_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaauthority',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address (use \\n for line breaks)', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='mediaauthority',
            name='broadcast_end',
            field=models.TimeField(blank=True, help_text='Default broadcast end time (HH:MM format)', null=True, verbose_name='Broadcast End Time'),
        ),
        migrations.AddField(
            model_name='mediaauthority',
            name='broadcast_start',
            field=models.TimeField(blank=True, help_text='Default broadcast start time (HH:MM format)', null=True, verbose_name='Broadcast Start Time'),
        ),
        migrations.AddField(
            model_name='mediaauthority',
            name='description',
            field=models.TextField(blank=True, help_text='Organization description or welcome message', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='mediaauthority',
            name='email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='mediaauthority',
            name='fax',
            field=models.CharField(blank=True, help_text='Fax number', max_length=50, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='mediaauthority',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Opening hours (use \\n for line breaks)', verbose_name='Opening Hours'),
        ),
        migrations.AddField(
            model_name='mediaauthority',
            name='organization_owner',
            field=models.CharField(blank=True, help_text='Organization owner identifier', max_length=100, verbose_name='Organization Owner'),
        ),
        migrations.AddField(
            model_name='mediaauthority',
            name='peertube_channel',
            field=models.CharField(blank=True, help_text='PeerTube channel identifier', max_length=255, verbose_name='PeerTube Channel'),
        ),
        migrations.AddField(
            model_name='mediaauthority',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=50, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='mediaauthority',
            name='state_media_institution',
            field=models.CharField(blank=True, help_text='State media institution (e.g., MSA)', max_length=50, verbose_name='State Media Institution'),
        ),
        migrations.AddField(
            model_name='mediaauthority',
            name='website',
            field=models.URLField(blank=True, help_text='Organization website URL', verbose_name='Website'),
        ),
    ]
