# Generated by Django 5.2.7 on 2026-01-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_mediaauthority_address_mediaauthority_broadcast_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Open Channel Merseburg-Querfurt e.V.', help_text='Full name of the organization', max_length=255, verbose_name='Organization Name')),
                ('short_name', models.CharField(default='OK Merseburg', help_text='Short name of the organization', max_length=150, verbose_name='Short Name')),
                ('website', models.URLField(blank=True, help_text='Organization website URL', max_length=255, verbose_name='Website')),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=255, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, help_text='Fax number', max_length=50, verbose_name='Fax')),
                ('address', models.TextField(blank=True, help_text='Organization address (multiline)', verbose_name='Address')),
                ('description', models.TextField(blank=True, help_text='Welcome message or organization description', verbose_name='Description')),
                ('opening_hours', models.TextField(blank=True, help_text='Opening hours (multiline)', verbose_name='Opening Hours')),
                ('state_media_institution', models.CharField(default='MSA', help_text='Regulatory institution code (MSA, LFK, BLM, etc.)', max_length=50, verbose_name='State Media Institution')),
                ('organization_owner', models.CharField(default='OKMQ', help_text='Owner/operator identifier (matches MediaAuthority name)', max_length=150, verbose_name='Organization Owner')),
                ('broadcast_start', models.TimeField(default='06:00', help_text='Default broadcast start time', verbose_name='Broadcast Start Time')),
                ('broadcast_end', models.TimeField(default='23:00', help_text='Default broadcast end time', verbose_name='Broadcast End Time')),
                ('peertube_channel', models.CharField(blank=True, help_text='PeerTube channel identifier', max_length=255, verbose_name='PeerTube Channel')),
                ('datenschutz', models.TextField(blank=True, help_text='Privacy policy text', verbose_name='Privacy Policy (Datenschutz)')),
                ('impressum', models.TextField(blank=True, help_text='Legal imprint text', verbose_name='Imprint (Impressum)')),
                ('agb', models.TextField(blank=True, help_text='Terms and conditions text', verbose_name='Terms and Conditions (AGB)')),
            ],
            options={
                'verbose_name': 'Organization Configuration',
                'verbose_name_plural': 'Organization Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='mediaauthority',
            name='address',
        ),
        migrations.RemoveField(
            model_name='mediaauthority',
            name='broadcast_end',
        ),
        migrations.RemoveField(
            model_name='mediaauthority',
            name='broadcast_start',
        ),
        migrations.RemoveField(
            model_name='mediaauthority',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mediaauthority',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mediaauthority',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='mediaauthority',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='mediaauthority',
            name='organization_owner',
        ),
        migrations.RemoveField(
            model_name='mediaauthority',
            name='peertube_channel',
        ),
        migrations.RemoveField(
            model_name='mediaauthority',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='mediaauthority',
            name='state_media_institution',
        ),
        migrations.RemoveField(
            model_name='mediaauthority',
            name='website',
        ),
    ]
