# Generated by Django 5.2.7 on 2026-01-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_organizationconfig_remove_mediaauthority_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaauthority',
            name='name',
            field=models.CharField(default='OK Merseburg', max_length=150, unique=True, verbose_name='Media Authority'),
        ),
    ]
