# Generated by Django 6.0.6 on 2026-06-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_organizationconfig_bundesland_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='okuser',
            name='staff_signature_points',
            field=models.JSONField(blank=True, default=None, help_text='Biometric stroke points for re-editing the signature on the canvas.', null=True, verbose_name='Staff signature points'),
        ),
        migrations.AddField(
            model_name='okuser',
            name='staff_signature_svg',
            field=models.TextField(blank=True, help_text="SVG path data of the staff member's hand-drawn signature for Freistellung PDF.", null=True, verbose_name='Staff signature SVG'),
        ),
        migrations.AlterField(
            model_name='organizationconfig',
            name='bundesland',
            field=models.CharField(choices=[('Baden-Württemberg', 'Baden-Württemberg'), ('Bayern', 'Bayern'), ('Berlin', 'Berlin'), ('Brandenburg', 'Brandenburg'), ('Bremen', 'Bremen'), ('Hamburg', 'Hamburg'), ('Hessen', 'Hessen'), ('Mecklenburg-Vorpommern', 'Mecklenburg-Vorpommern'), ('Niedersachsen', 'Niedersachsen'), ('Nordrhein-Westfalen', 'Nordrhein-Westfalen'), ('Rheinland-Pfalz', 'Rheinland-Pfalz'), ('Saarland', 'Saarland'), ('Sachsen', 'Sachsen'), ('Sachsen-Anhalt', 'Sachsen-Anhalt'), ('Schleswig-Holstein', 'Schleswig-Holstein'), ('Thüringen', 'Thüringen')], default='Sachsen-Anhalt', help_text='German federal state written to exchange metadata; code is generated automatically', max_length=64, verbose_name='Bundesland'),
        ),
    ]
