# Generated by Django 6.0.6 on 2026-07-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_okuser_staff_signature_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rental_only',
            field=models.BooleanField(default=False, help_text='The profile may only rent equipment. Mutually exclusive with member: a profile is either a member or rental only, never both.', verbose_name='rental only'),
        ),
    ]
