# Generated by Django 6.0.6 on 2026-08-09 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_profile_rental_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationconfig',
            name='media_authority',
            field=models.ForeignKey(blank=True, help_text='Which "Offener Kanal" this installation is. Used to tell own productions from material of other channels.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_configs', to='registration.mediaauthority', verbose_name='Own Media Authority'),
        ),
    ]
