# Generated by Django 6.0.6 on 2026-08-13 21:19

import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_seed_organization_media_authority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaauthority',
            name='name',
            field=models.CharField(default=registration.models.default_media_authority_name, max_length=150, unique=True, verbose_name='Media Authority'),
        ),
    ]
