"""Django settings for ok_tools project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from django.contrib.messages import constants as messages
from django.utils.translation import gettext_lazy as _
from pathlib import Path
import dj_database_url
import logging
import os
from datetime import timedelta
from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured


# Logger for settings.py
logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# ENV Helper Functions
# =============================================================================

def get_env(key: str, default=None, required: bool = False, cast: type = str):
    """
    Get environment variable with type casting and validation.
    
    Args:
        key: Environment variable name
        default: Default value if not found
        required: Raise exception if not found and no default
        cast: Type to cast the value to (str, int, bool, list)
    
    Returns:
        Casted value or default
        
    Raises:
        ImproperlyConfigured: If required variable is missing
    """
    value = os.getenv(key, default)
    
    if required and value is None:
        raise ImproperlyConfigured(f"Required environment variable '{key}' is not set")
    
    if value is None:
        return None
    
    # Type casting
    if cast == bool:
        return str(value).lower() in ('true', '1', 'yes', 'on')
    elif cast == int:
        try:
            return int(value)
        except (ValueError, TypeError):
            logger.warning(f"Cannot cast '{key}={value}' to int, using default: {default}")
            return default if default is not None else 0
    elif cast == list:
        # Comma-separated list
        return [item.strip() for item in str(value).split(',') if item.strip()]
    else:
        return str(value)

def get_env_list(key: str, default: list = None, separator: str = ','):
    """Get environment variable as list."""
    value = os.getenv(key)
    if not value:
        return default or []
    return [item.strip() for item in value.split(separator) if item.strip()]

# =============================================================================
# Helper for Celery Beat Schedules
# =============================================================================

def parse_crontab_env(env_key: str, default: str = '0 0 * * *'):
    """Parse crontab string from environment variable."""
    crontab_string = get_env(env_key, default=default)
    parts = crontab_string.split()
    
    # Ensure we have exactly 5 parts
    while len(parts) < 5:
        parts.append('*')
    
    return crontab(
        minute=parts[0],
        hour=parts[1],
        day_of_month=parts[2],
        month_of_year=parts[3],
        day_of_week=parts[4],
    )

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env('DJANGO_SECRET_KEY', required=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env('DEBUG', default=False, cast=bool)

# Allowed hosts configuration
allowed_hosts_str = get_env('ALLOWED_HOSTS', default='localhost')
if ',' in allowed_hosts_str:
    ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_str.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = allowed_hosts_str.split()

# Loglevel
DJANGO_LOG_LEVEL = get_env('DJANGO_LOG_LEVEL', default='INFO')

# Application definition

INSTALLED_APPS = [
    "django_prometheus",
    "ok_tools",
    "registration",
    "licenses",
    "projects",
    "contributions",
    "planung",
    "inventory",
    "dashboard",
    "rental",
    "media_files",
    "django_celery_results",
    "django_celery_beat",
    "rest_framework",
    "rest_framework.authtoken",
    "crispy_forms",
    "crispy_bootstrap4",
    "admin_auto_filters",
    "django_admin_listfilter_dropdown",
    "django_extensions",
    "icalendar",
    "import_export",
    "rangefilter",
    "tablib",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # WhiteNoise must be after SecurityMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "ok_tools.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "licenses" / "templates",
            BASE_DIR / "ok_tools" / "templates",
            BASE_DIR / "registration" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "registration.context_processors.context",
                "ok_tools.context_processors.bootstrap_context",
            ],
        },
    },
]


WSGI_APPLICATION = "ok_tools.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


use_secure_settings = get_env('USE_SECURE_SETTINGS', default=False, cast=bool)

if use_secure_settings:
    CSRF_TRUSTED_ORIGINS = [f"https://{hosts}" for hosts in ALLOWED_HOSTS]
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CORS_ORIGIN_WHITELIST = [f"https://{hosts}" for hosts in ALLOWED_HOSTS]
    USE_X_FORWARDED_HOST = True

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = get_env('LANGUAGE_CODE', default='de-de')

TIME_ZONE = get_env('TIME_ZONE', default='Europe/Berlin')

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [BASE_DIR / "ok_tools/locale"]

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT = get_env('STATIC_ROOT', default='staticfiles/')
STATIC_URL = "/static/"

MEDIA_ROOT = get_env('MEDIA_ROOT', default='media/')
MEDIA_URL = "/media/"

# ManifestStaticFilesStorage is recommended in production, to prevent outdatedhttp://localhost:8000/
# JavaScript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See
# https://docs.djangoproject.com/en/3.1/ref/contrib/staticfiles/#manifeststaticfilesstorage
# Allow overriding storage backend from environment variable
_static_storage_backend = get_env('STATIC_STORAGE_BACKEND', default=None)
if _static_storage_backend:
    STATICFILES_STORAGE = _static_storage_backend
else:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

# WhiteNoise configuration for serving static files
# Only apply WhiteNoise settings when using WhiteNoise storage
if 'whitenoise' in STATICFILES_STORAGE.lower():
    WHITENOISE_USE_FINDERS = True  # Allow WhiteNoise to find files during development
    WHITENOISE_AUTOREFRESH = DEBUG  # Auto-refresh in debug mode

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# authenticatable users
AUTH_USER_MODEL = "registration.OKUser"
AUTHENTICATION_BACKENDS = ["registration.backends.EmailBackend"]

# Phone Number Validation
PHONENUMBER_DEFAULT_REGION = get_env('PHONENUMBER_DEFAULT_REGION', default='DE')

# Date format
DATE_INPUT_FORMATS = get_env('DATE_INPUT_FORMATS', default='%d.%m.%Y')

# email
# send mails to stdout

mail_dev_settings = get_env('MAIL_DEV_SETTINGS', default=True, cast=bool)

if mail_dev_settings:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_HOST = get_env('EMAIL_HOST', default='')
EMAIL_PORT = get_env('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = get_env('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = get_env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = get_env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = get_env('DEFAULT_FROM_EMAIL', default='webmaster@localhost')


# name of OK
# Support both ORG_* and OK_* prefixes for backward compatibility
# ORG_* takes precedence over OK_*
# Use os.getenv directly to check if variable exists (returns None if not set)
_org_name = os.getenv('ORG_NAME')
OK_NAME = _org_name if _org_name is not None else get_env('OK_NAME', default=_("Open Channel Merseburg-Querfurt e.V."))
_org_short_name = os.getenv('ORG_SHORT_NAME')
OK_NAME_SHORT = _org_short_name if _org_short_name is not None else get_env('OK_NAME_SHORT', default=_("OK Merseburg"))

# Organization settings
# Support both ORG_* and OK_* prefixes for backward compatibility
# ORG_* takes precedence over OK_*
_org_website = os.getenv('ORG_WEBSITE')
OK_WEBSITE = _org_website if _org_website is not None else get_env('OK_WEBSITE', default='')
_org_email = os.getenv('ORG_EMAIL')
OK_EMAIL = _org_email if _org_email is not None else get_env('OK_EMAIL', default='')
_org_address = os.getenv('ORG_ADDRESS')
OK_ADDRESS = _org_address if _org_address is not None else get_env('OK_ADDRESS', default='')
_org_phone = os.getenv('ORG_PHONE')
OK_PHONE = _org_phone if _org_phone is not None else get_env('OK_PHONE', default='')
_org_fax = os.getenv('ORG_FAX')
OK_FAX = _org_fax if _org_fax is not None else get_env('OK_FAX', default='')
_org_description = os.getenv('ORG_DESCRIPTION')
OK_DESCRIPTION = _org_description if _org_description is not None else get_env('OK_DESCRIPTION', default='')
_org_opening_hours = os.getenv('ORG_OPENING_HOURS')
OK_OPENING_HOURS = _org_opening_hours if _org_opening_hours is not None else get_env('OK_OPENING_HOURS', default='')
STATE_MEDIA_INSTITUTION = get_env('STATE_MEDIA_INSTITUTION', default='MSA')
_org_owner = os.getenv('ORG_ORGANIZATION_OWNER')
ORGANIZATION_OWNER = _org_owner if _org_owner is not None else get_env('ORGANIZATION_OWNER', default='OKMQ')

# fixed duration of a screen board (Bildschirmtafel) in seconds
SCREEN_BOARD_DURATION = get_env('SCREEN_BOARD_DURATION', default=20, cast=int)

# Which site should be seen after log in and log out
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# bootstrap
CRISPY_TEMPLATE_PACK = "bootstrap4"

# bootstrap message tags
# For warnings and errors both, bootstrap tag (alert-*) and django tag,
# is set to support user side and admin side with colorfully messages.
MESSAGE_TAGS = {
    messages.DEBUG: "alert-secondary",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning warning",
    messages.ERROR: "alert-danger error",
}

# path to legacy data
LEGACY_DATA = "../legacy_data/data.xlsx"

# Backup directory - read from environment
BACKUP_DIR = get_env('BACKUP_DIR', default='backups/')

# Broadcast time settings for planning - read from environment
BROADCAST_START = get_env('BROADCAST_START', default='06:00')
BROADCAST_END = get_env('BROADCAST_END', default='23:00')

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "timestamp": {
            "format": "{asctime} {levelname} {message}",
            "style": "{",
        },
        "levelname": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(name)s %(levelname)s %(pathname)s %(lineno)d %(message)s",
        },
    },
    "handlers": {
        "file": {
            "level": DJANGO_LOG_LEVEL,
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "ok_tools-debug.log"),
            "formatter": "timestamp",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "dashboard": {
            "handlers": ["file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "media_files": {
            "handlers": ["file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "registration": {
            "handlers": ["file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "console": {
            "handlers": ["console"],
            "level": "CRITICAL",
            "propagate": True,
        },
        "celery": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "celery.task": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "celery.worker": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Bootstrap settings
BOOTSTRAP_VERSION = get_env('BOOTSTRAP_VERSION', default='5.3.2')
BOOTSTRAP_CDN_URL = f"https://cdn.jsdelivr.net/npm/bootstrap@{BOOTSTRAP_VERSION}"
BOOTSTRAP_ICONS_VERSION = get_env('BOOTSTRAP_ICONS_VERSION', default='1.1.1')
BOOTSTRAP_ICONS_URL = f"https://cdn.jsdelivr.net/npm/bootstrap-icons@{BOOTSTRAP_ICONS_VERSION}"

# Cache Configuration
# Get cache backend from environment or use Redis if available
cache_backend = get_env('CACHE_BACKEND', default=None)
cache_timeout = get_env('CACHE_TIMEOUT', default=300, cast=int)
cache_location = get_env('CACHE_LOCATION', default=None)

if cache_backend:
    # Use configured backend from environment
    CACHES = {
        'default': {
            'BACKEND': cache_backend,
            'LOCATION': cache_location or 'cache',
            'TIMEOUT': cache_timeout,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
elif cache_location:
    # Use Redis if location is specified
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': cache_location,
            'TIMEOUT': cache_timeout,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
else:
    # Default: Use Redis from Celery broker URL (same Redis instance)
    # Extract Redis URL from Celery broker
    celery_broker = get_env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')
    # Use database 1 for cache (Celery uses database 0)
    if 'redis://' in celery_broker:
        # Replace database number with 1 for cache
        cache_redis_url = celery_broker.rsplit('/', 1)[0] + '/1'
    else:
        cache_redis_url = 'redis://127.0.0.1:6379/1'
    
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': cache_redis_url,
            'TIMEOUT': cache_timeout,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }

# Celery Configuration
CELERY_BROKER_URL = get_env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')
# Use django-celery-results backend to store results in database (visible in admin)
# Allow both 'django-db' (short form) and full path for backward compatibility
_result_backend = get_env('CELERY_RESULT_BACKEND', default='django-db')
if _result_backend == 'django-db':
    CELERY_RESULT_BACKEND = 'django_celery_results.backends.database:DatabaseBackend'
else:
    CELERY_RESULT_BACKEND = _result_backend

# Celery Configuration Options
CELERY_TIMEZONE = get_env('TIME_ZONE', default='Europe/Berlin')
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 10
# Enable extended result format to store more task information
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_BACKEND_ALWAYS_RETRY = True
CELERY_RESULT_BACKEND_MAX_RETRIES = 10

# Use django-celery-beat scheduler (allows managing periodic tasks via admin)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery Beat Schedule from environment variables
# Note: Tasks can also be managed via django-celery-beat admin interface
CELERY_BEAT_SCHEDULE = {
    'expire_rentals': {
        'task': 'ok_tools.tasks.run_expire_room_rentals_task',
        'schedule': parse_crontab_env('CELERY_BEAT_EXPIRE_RENTALS', '*/30 * * * *'),
    },
    'cleanup_old_backups': {
        'task': 'ok_tools.tasks.cleanup_old_backups_task',
        'schedule': parse_crontab_env('CELERY_BEAT_CLEANUP_OLD_BACKUPS', '0 2 * * *'),
    },
    'run_backup_db': {
        'task': 'ok_tools.tasks.run_backup_db_task',
        'schedule': parse_crontab_env('CELERY_BEAT_RUN_BACKUP_DB', '0 3 * * *'),
    },
    'auto_scan': {
        'task': 'media_files.tasks.run_auto_scan',
        'schedule': parse_crontab_env('CELERY_BEAT_AUTO_SCAN', '0 */2 * * *'),
    },
    'link_orphan_licenses': {
        'task': 'media_files.tasks.run_link_orphan_licenses',
        'schedule': parse_crontab_env('CELERY_BEAT_LINK_ORPHAN_LICENSES', '0 3 * * *'),
    },
    'sync_licenses_videos': {
        'task': 'media_files.tasks.run_sync_licenses_videos',
        'schedule': parse_crontab_env('CELERY_BEAT_SYNC_LICENSES_VIDEOS', '0 4 * * *'),
    },
    'update_video_metadata': {
        'task': 'media_files.tasks.run_update_video_metadata',
        'schedule': parse_crontab_env('CELERY_BEAT_UPDATE_VIDEO_METADATA', '0 1 1 * *'),
        'kwargs': {'missing_only': True},
    },
}
