"""Django settings for ok_tools project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from celery.schedules import crontab
from datetime import timedelta
from django.contrib.messages import constants as messages
from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import gettext_lazy as _
from pathlib import Path
import dj_database_url
import logging
import os


# Logger for settings.py
logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# ENV Helper Functions
# =============================================================================

def get_env(key: str, default=None, required: bool = False, cast: type = str):
    """
    Get environment variable with type casting and validation.
    
    Args:
        key: Environment variable name
        default: Default value if not found
        required: Raise exception if not found and no default
        cast: Type to cast the value to (str, int, bool, list)
    
    Returns:
        Casted value or default
        
    Raises:
        ImproperlyConfigured: If required variable is missing
    """
    value = os.getenv(key, default)
    
    if required and value is None:
        raise ImproperlyConfigured(f"Required environment variable '{key}' is not set")
    
    if value is None:
        return None
    
    # Type casting
    if cast == bool:
        return str(value).lower() in ('true', '1', 'yes', 'on')
    elif cast == int:
        try:
            return int(value)
        except (ValueError, TypeError):
            logger.warning(f"Cannot cast '{key}={value}' to int, using default: {default}")
            return default if default is not None else 0
    elif cast == list:
        # Comma-separated list
        return [item.strip() for item in str(value).split(',') if item.strip()]
    else:
        return str(value)

def get_env_list(key: str, default: list = None, separator: str = ','):
    """Get environment variable as list."""
    value = os.getenv(key)
    if not value:
        return default or []
    return [item.strip() for item in value.split(separator) if item.strip()]

# =============================================================================
# Helper for Celery Beat Schedules
# =============================================================================

def parse_crontab_env(env_key: str, default: str = '0 0 * * *'):
    """Parse crontab string from environment variable."""
    crontab_string = get_env(env_key, default=default)
    parts = crontab_string.split()
    
    # Ensure we have exactly 5 parts
    while len(parts) < 5:
        parts.append('*')
    
    return crontab(
        minute=parts[0],
        hour=parts[1],
        day_of_month=parts[2],
        month_of_year=parts[3],
        day_of_week=parts[4],
    )

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env('DJANGO_SECRET_KEY', required=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env('DEBUG', default=False, cast=bool)

# Allowed hosts configuration
allowed_hosts_str = get_env('ALLOWED_HOSTS', default='localhost')
if ',' in allowed_hosts_str:
    ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_str.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = allowed_hosts_str.split()

# =============================================================================
# Site / URLs
# =============================================================================
SITE_BASE_URL = get_env('SITE_BASE_URL', default='')
if not SITE_BASE_URL:
    # Best-effort fallback for building absolute URLs in emails.
    # Prefer explicit SITE_BASE_URL in production.
    default_scheme = 'http' if DEBUG else 'https'
    fallback_host = next((h for h in ALLOWED_HOSTS if h and h != '*'), 'localhost')
    SITE_BASE_URL = f"{default_scheme}://{fallback_host}"

# =============================================================================
# Module-specific settings moved to module configs
# =============================================================================
# The following settings are now managed through module configuration models:
# - Registration: registration.config (RegistrationConfig model)
# - Rental: rental.config (RentalConfig model)
# - Media Files: media_files.config (MediaFilesConfig model)
# - Tools: tools.models (ToolsConfig model)
# - Austausch: austausch.models (ExchangeConfig model)
#
# For backward compatibility, these settings are still available via helper functions
# that fall back to environment variables if config models are not available.
# See module config.py files for details.

# Loglevel
DJANGO_LOG_LEVEL = get_env('DJANGO_LOG_LEVEL', default='INFO')

# Application definition

INSTALLED_APPS = [
    "django_prometheus",
    "ok_tools",
    "registration",
    "django_celery_results",
    "django_celery_beat",
    "rest_framework",
    "rest_framework.authtoken",
    "crispy_forms",
    "crispy_bootstrap4",
    "admin_auto_filters",
    "django_admin_listfilter_dropdown",
    "django_extensions",
    "icalendar",
    "import_export",
    "rangefilter",
    "tablib",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# =============================================================================
# Module flags
# =============================================================================

LICENSES_ENABLED = get_env('LICENSES_ENABLED', default=True, cast=bool)
# Contributions depends on licenses - automatically enabled if licenses is enabled
CONTRIBUTIONS_ENABLED = LICENSES_ENABLED

RENTAL_ENABLED = get_env('RENTAL_ENABLED', default=False, cast=bool)
if RENTAL_ENABLED:
    INVENTORY_ENABLED = True
else:
    INVENTORY_ENABLED = get_env('INVENTORY_ENABLED', default=False, cast=bool)

PROJECTS_ENABLED = get_env('PROJECTS_ENABLED', default=False, cast=bool)
PLANUNG_ENABLED = get_env('PLANUNG_ENABLED', default=False, cast=bool)
MEDIA_FILES_ENABLED = get_env('MEDIA_FILES_ENABLED', default=False, cast=bool)

# Admin analytics dashboard (requires optional modules below)
DASHBOARD_ENABLED = get_env('DASHBOARD_ENABLED', default=False, cast=bool)

# Austausch and Tools modules (already optional)
AUSTAUSCH_ENABLED = get_env('AUSTAUSCH_ENABLED', default=False, cast=bool)
TOOLS_ENABLED = get_env('TOOLS_ENABLED', default=False, cast=bool)

# Enforce dependencies for licenses-related modules
if not LICENSES_ENABLED:
    CONTRIBUTIONS_ENABLED = False
    PLANUNG_ENABLED = False
    MEDIA_FILES_ENABLED = False
    AUSTAUSCH_ENABLED = False

# Apply module flags
if LICENSES_ENABLED:
    INSTALLED_APPS.append("licenses")
    INSTALLED_APPS.append("contributions")  # Contributions depends on licenses

if INVENTORY_ENABLED:
    INSTALLED_APPS.append("inventory")
if RENTAL_ENABLED:
    INSTALLED_APPS.append("rental")

if PROJECTS_ENABLED:
    INSTALLED_APPS.append("projects")
if PLANUNG_ENABLED:
    INSTALLED_APPS.append("planung")
if MEDIA_FILES_ENABLED:
    INSTALLED_APPS.append("media_files")

# Admin analytics dashboard - works with any combination of enabled modules
# Shows statistics only for modules that are enabled
# Minimum requirement: LICENSES_ENABLED (core module for dashboard)
if DASHBOARD_ENABLED and not LICENSES_ENABLED:
    DASHBOARD_ENABLED = False

if DASHBOARD_ENABLED:
    INSTALLED_APPS.append("dashboard")

if AUSTAUSCH_ENABLED:
    INSTALLED_APPS.append("austausch")

if TOOLS_ENABLED:
    INSTALLED_APPS.append("tools")

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # WhiteNoise must be after SecurityMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "ok_tools.middleware.ForceDefaultLanguageMiddleware",  # Set default language in session BEFORE LocaleMiddleware
    "django.middleware.locale.LocaleMiddleware",  # Must be after SessionMiddleware to use session language
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "ok_tools.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "licenses" / "templates",
            BASE_DIR / "ok_tools" / "templates",
            BASE_DIR / "registration" / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "registration.context_processors.context",
                "ok_tools.context_processors.bootstrap_context",
                "ok_tools.context_processors.user_display_name",
                "ok_tools.context_processors.nextcloud_context",
                "ok_tools.context_processors.dashboard_theme_context",
                "ok_tools.context_processors.module_flags",
            ],
        },
    },
]


WSGI_APPLICATION = "ok_tools.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=get_env('DATABASE_CONN_MAX_AGE', default=600, cast=int),
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


use_secure_settings = get_env('USE_SECURE_SETTINGS', default=False, cast=bool)

if use_secure_settings:
    CSRF_TRUSTED_ORIGINS = [f"https://{hosts}" for hosts in ALLOWED_HOSTS]
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CORS_ORIGIN_WHITELIST = [f"https://{hosts}" for hosts in ALLOWED_HOSTS]
    USE_X_FORWARDED_HOST = True

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

TIME_ZONE = get_env('TIME_ZONE', default='Europe/Berlin')

USE_I18N = True

USE_L10N = True

DATE_FORMAT = 'd.m.Y'
DATETIME_FORMAT = 'd.m.Y H:i'
SHORT_DATE_FORMAT = 'd.m.Y'
SHORT_DATETIME_FORMAT = 'd.m.Y H:i'

USE_TZ = True

LOCALE_PATHS = [BASE_DIR / "ok_tools/locale"]

# Supported languages for i18n
# Explicitly set LANGUAGES to prevent Django from using Accept-Language header
# which can cause inconsistent language selection (sometimes English, sometimes German)
supported_languages = get_env('I18N_SUPPORTED_LANGUAGES', default='de,en')
default_language = get_env('I18N_DEFAULT_LANGUAGE', default='de')

# Normalize default language to base code (de-de -> de, en-us -> en)
normalized_default_language = default_language.lower().split('-')[0] if default_language else 'de'

# Set LANGUAGE_CODE from I18N_DEFAULT_LANGUAGE if LANGUAGE_CODE is not explicitly set
# This ensures consistency between default language and LANGUAGE_CODE
# Support both LANGUAGE_CODE and DJANGO_LANGUAGE for backward compatibility
_language_code = get_env('LANGUAGE_CODE', default=None) or get_env('DJANGO_LANGUAGE', default=None)
if _language_code:
    # If LANGUAGE_CODE is explicitly set, use it (normalized)
    LANGUAGE_CODE = _language_code.lower().split('-')[0]
else:
    # If not set, use I18N_DEFAULT_LANGUAGE to ensure consistency
    LANGUAGE_CODE = normalized_default_language

# Parse supported languages from comma-separated string
language_list = [lang.strip() for lang in supported_languages.split(',') if lang.strip()]

# Map language codes to full names (Django expects short codes like 'de', 'en')
LANGUAGE_NAMES = {
    'de': 'German',
    'en': 'English',
}

# Build LANGUAGES tuple - Django expects format [('de', 'German'), ('en', 'English')]
# Normalize language codes (de-de -> de, en-us -> en)
LANGUAGES = []
for lang_code in language_list:
    # Extract base language code (de-de -> de, en-us -> en)
    normalized = lang_code.lower().split('-')[0]
    if normalized in LANGUAGE_NAMES:
        # Only add if not already in list (avoid duplicates)
        if (normalized, LANGUAGE_NAMES[normalized]) not in LANGUAGES:
            LANGUAGES.append((normalized, LANGUAGE_NAMES[normalized]))

# If no valid languages found, use default
if not LANGUAGES:
    LANGUAGES = [('de', 'German'), ('en', 'English')]

# Ensure default language is first in the list (highest priority)
if normalized_default_language in LANGUAGE_NAMES:
    default_tuple = (normalized_default_language, LANGUAGE_NAMES[normalized_default_language])
    # Move default to front if it exists
    if default_tuple in LANGUAGES:
        LANGUAGES.remove(default_tuple)
    LANGUAGES.insert(0, default_tuple)

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_ROOT = get_env('STATIC_ROOT', default='staticfiles/')
STATIC_URL = "/static/"

MEDIA_ROOT = get_env('MEDIA_ROOT', default='media/')
MEDIA_URL = "/media/"

# Django 5+: use STORAGES['staticfiles'] instead of the deprecated STATICFILES_STORAGE.
# ManifestStaticFilesStorage produces content-hashed URLs (e.g. wizard.jsx) to prevent
# stale browser cache. Allow overriding the backend via STATIC_STORAGE_BACKEND env var.
_static_storage_backend = get_env('STATIC_STORAGE_BACKEND', default=None)
if _static_storage_backend:
    _default_staticfiles_backend = _static_storage_backend
else:
    _default_staticfiles_backend = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": _default_staticfiles_backend,
    },
}

# WhiteNoise configuration for serving static files
# Only apply WhiteNoise settings when using WhiteNoise storage
if 'whitenoise' in _default_staticfiles_backend.lower():
    WHITENOISE_USE_FINDERS = True  # Allow WhiteNoise to find files during development
    WHITENOISE_AUTOREFRESH = DEBUG  # Auto-refresh in debug mode

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# authenticatable users
AUTH_USER_MODEL = "registration.OKUser"
AUTHENTICATION_BACKENDS = ["registration.backends.EmailBackend"]

# Phone Number Validation
PHONENUMBER_DEFAULT_REGION = get_env('PHONENUMBER_DEFAULT_REGION', default='DE')

# Date format
DATE_INPUT_FORMATS = get_env('DATE_INPUT_FORMATS', default='%d.%m.%Y')

# email
# send mails to stdout

mail_dev_settings = get_env('MAIL_DEV_SETTINGS', default=True, cast=bool)

if mail_dev_settings:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_HOST = get_env('EMAIL_HOST', default='')
EMAIL_PORT = get_env('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = get_env('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = get_env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = get_env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = get_env('DEFAULT_FROM_EMAIL', default='webmaster@localhost')


# name of OK
# Support both ORG_* and OK_* prefixes for backward compatibility
# ORG_* takes precedence over OK_*
# Use os.getenv directly to check if variable exists (returns None if not set)
_org_name = os.getenv('ORG_NAME')
OK_NAME = _org_name if _org_name is not None else get_env('OK_NAME', default="Open Channel Merseburg-Querfurt e.V.")
_org_short_name = os.getenv('ORG_SHORT_NAME')
OK_NAME_SHORT = _org_short_name if _org_short_name is not None else get_env('OK_NAME_SHORT', default="OK Merseburg")

# Organization settings
# Support both ORG_* and OK_* prefixes for backward compatibility
# ORG_* takes precedence over OK_*
_org_website = os.getenv('ORG_WEBSITE')
OK_WEBSITE = _org_website if _org_website is not None else get_env('OK_WEBSITE', default='')
_org_email = os.getenv('ORG_EMAIL')
OK_EMAIL = _org_email if _org_email is not None else get_env('OK_EMAIL', default='')
_org_address = os.getenv('ORG_ADDRESS')
OK_ADDRESS = (_org_address if _org_address is not None else get_env('OK_ADDRESS', default='')).replace('\\n', '\n')
_org_phone = os.getenv('ORG_PHONE')
OK_PHONE = _org_phone if _org_phone is not None else get_env('OK_PHONE', default='')
_org_fax = os.getenv('ORG_FAX')
OK_FAX = _org_fax if _org_fax is not None else get_env('OK_FAX', default='')
_org_description = os.getenv('ORG_DESCRIPTION')
OK_DESCRIPTION = _org_description if _org_description is not None else get_env('OK_DESCRIPTION', default='')
_org_opening_hours = os.getenv('ORG_OPENING_HOURS')
OK_OPENING_HOURS = (_org_opening_hours if _org_opening_hours is not None else get_env('OK_OPENING_HOURS', default='')).replace('\\n', '\n')
STATE_MEDIA_INSTITUTION = get_env('STATE_MEDIA_INSTITUTION', default='MSA')
_org_owner = os.getenv('ORG_ORGANIZATION_OWNER')
ORGANIZATION_OWNER = _org_owner if _org_owner is not None else get_env('ORGANIZATION_OWNER', default='OKMQ')

# Screen board duration - now managed via LicensesConfig model
# See licenses.config for helper function
# Kept for backward compatibility
SCREEN_BOARD_DURATION = get_env('SCREEN_BOARD_DURATION', default=20, cast=int)

# Which site should be seen after log in and log out
# Use named URL patterns so redirects stay stable if paths change.
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# bootstrap
CRISPY_TEMPLATE_PACK = "bootstrap4"

# bootstrap message tags
# For warnings and errors both, bootstrap tag (alert-*) and django tag,
# is set to support user side and admin side with colorfully messages.
MESSAGE_TAGS = {
    messages.DEBUG: "alert-secondary",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning warning",
    messages.ERROR: "alert-danger error",
}

# path to legacy data
LEGACY_DATA = "../legacy_data/data.xlsx"

# Backup directory - read from environment
BACKUP_DIR = get_env('BACKUP_DIR', default='backups/')

# Broadcast time settings for planning - read from environment
# Support both ORG_BROADCAST_* and BROADCAST_* prefixes for backward compatibility
# ORG_BROADCAST_* takes precedence over BROADCAST_*
_org_broadcast_start = os.getenv('ORG_BROADCAST_START')
BROADCAST_START = _org_broadcast_start if _org_broadcast_start is not None else get_env('BROADCAST_START', default='06:00')
_org_broadcast_end = os.getenv('ORG_BROADCAST_END')
BROADCAST_END = _org_broadcast_end if _org_broadcast_end is not None else get_env('BROADCAST_END', default='23:00')

# PeerTube channel - read from environment
# Support both ORG_PEERTUBE_CHANNEL and PEERTUBE_CHANNEL for backward compatibility
# ORG_PEERTUBE_CHANNEL takes precedence over PEERTUBE_CHANNEL
_org_peertube_channel = os.getenv('ORG_PEERTUBE_CHANNEL')
PEERTUBE_CHANNEL = _org_peertube_channel if _org_peertube_channel is not None else get_env('PEERTUBE_CHANNEL', default='')

# Nextcloud integration settings
NEXTCLOUD_ENABLED = get_env('NEXTCLOUD_ENABLED', default=False, cast=bool)

if NEXTCLOUD_ENABLED:
    NEXTCLOUD_URL = get_env('NEXTCLOUD_URL', required=True)
    NEXTCLOUD_USERNAME = get_env('NEXTCLOUD_USERNAME', required=True)
    NEXTCLOUD_PASSWORD = get_env('NEXTCLOUD_PASSWORD', required=True)
    NEXTCLOUD_UPLOAD_FOLDER = get_env('NEXTCLOUD_UPLOAD_FOLDER', default='Freistellungen/Videos')
    NEXTCLOUD_WEBDAV_PATH = get_env('NEXTCLOUD_WEBDAV_PATH', default='/remote.php/dav/files/{username}/')
    # Chunked upload settings for files > threshold
    NEXTCLOUD_CHUNKED_UPLOAD_ENABLED = get_env(
        'NEXTCLOUD_CHUNKED_UPLOAD_ENABLED', default=True, cast=bool
    )
    NEXTCLOUD_CHUNKED_UPLOAD_THRESHOLD = get_env(
        'NEXTCLOUD_CHUNKED_UPLOAD_THRESHOLD', default=100, cast=int
    )  # MB - files larger than this use chunked upload
    NEXTCLOUD_CHUNK_SIZE = get_env(
        'NEXTCLOUD_CHUNK_SIZE', default=10, cast=int
    )  # MB - size of each chunk
else:
    # Set defaults when disabled to avoid errors
    NEXTCLOUD_URL = ''
    NEXTCLOUD_USERNAME = ''
    NEXTCLOUD_PASSWORD = ''
    NEXTCLOUD_UPLOAD_FOLDER = ''
    NEXTCLOUD_WEBDAV_PATH = '/remote.php/dav/files/{username}/'
    NEXTCLOUD_CHUNKED_UPLOAD_ENABLED = False
    NEXTCLOUD_CHUNKED_UPLOAD_THRESHOLD = 100  # MB
    NEXTCLOUD_CHUNK_SIZE = 10  # MB

# Registration form settings - now managed via RegistrationConfig model
# See registration.config for helper functions

# Tools-specific settings
TOOLS_STORAGE_PATH = get_env('TOOLS_STORAGE_PATH', default='tools/storage/')
TOOLS_OUTPUT_PATH = get_env('TOOLS_OUTPUT_PATH', default='tools/output/')
TOOLS_MAX_UPLOAD_SIZE = get_env('TOOLS_MAX_UPLOAD_SIZE', default=500, cast=int)  # MB
TOOLS_FFMPEG_PATH = get_env('TOOLS_FFMPEG_PATH', default='ffmpeg')
TOOLS_FFPROBE_PATH = get_env('TOOLS_FFPROBE_PATH', default='ffprobe')

# Nextcloud Calendar integration settings (CalDAV)
NEXTCLOUD_CALENDAR_ENABLED = get_env('NEXTCLOUD_CALENDAR_ENABLED', default=False, cast=bool)

if NEXTCLOUD_CALENDAR_ENABLED:
    # CalDAV base URL (e.g., https://cloud.lokalmedial.de/remote.php/dav/calendars)
    NEXTCLOUD_CALDAV_BASE_URL = get_env(
        'NEXTCLOUD_CALDAV_BASE_URL',
        default=None
    )
    # If not set, try to construct from NEXTCLOUD_URL
    if not NEXTCLOUD_CALDAV_BASE_URL and NEXTCLOUD_ENABLED:
        NEXTCLOUD_CALDAV_BASE_URL = f"{NEXTCLOUD_URL.rstrip('/')}/remote.php/dav/calendars"
    
    # Calendar service account credentials (can be different from file upload account)
    NEXTCLOUD_CALENDAR_USERNAME = get_env('NEXTCLOUD_CALENDAR_USERNAME', default=None)
    NEXTCLOUD_CALENDAR_PASSWORD = get_env('NEXTCLOUD_CALENDAR_PASSWORD', default=None)
    
    # If not set, fall back to main Nextcloud credentials
    if not NEXTCLOUD_CALENDAR_USERNAME and NEXTCLOUD_ENABLED:
        NEXTCLOUD_CALENDAR_USERNAME = NEXTCLOUD_USERNAME
    if not NEXTCLOUD_CALENDAR_PASSWORD and NEXTCLOUD_ENABLED:
        NEXTCLOUD_CALENDAR_PASSWORD = NEXTCLOUD_PASSWORD
    
    # Default calendar name for all rooms (if set, all rooms will use this calendar)
    NEXTCLOUD_DEFAULT_CALENDAR_NAME = get_env('NEXTCLOUD_DEFAULT_CALENDAR_NAME', default=None)
    
    # Room to calendar mapping (room name/slug -> calendar name in Nextcloud)
    # Format: "room_name:calendar_name,room_id:calendar_name"
    # Only used if NEXTCLOUD_DEFAULT_CALENDAR_NAME is not set
    room_calendars_str = get_env('NEXTCLOUD_ROOM_CALENDARS', default='')
    NEXTCLOUD_ROOM_CALENDARS = {}
    if room_calendars_str:
        for mapping in room_calendars_str.split(','):
            if ':' in mapping:
                room_key, calendar_name = mapping.split(':', 1)
                NEXTCLOUD_ROOM_CALENDARS[room_key.strip()] = calendar_name.strip()
else:
    NEXTCLOUD_CALDAV_BASE_URL = ''
    NEXTCLOUD_CALENDAR_USERNAME = ''
    NEXTCLOUD_CALENDAR_PASSWORD = ''
    NEXTCLOUD_DEFAULT_CALENDAR_NAME = None
    NEXTCLOUD_ROOM_CALENDARS = {}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "timestamp": {
            "format": "{asctime} {levelname} {message}",
            "style": "{",
        },
        "levelname": {
            "format": "{levelname} {message}",
            "style": "{",
        },
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(name)s %(levelname)s %(pathname)s %(lineno)d %(message)s",
        },
    },
    "handlers": {
        "file": {
            "level": DJANGO_LOG_LEVEL,
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "ok_tools-debug.log"),
            "formatter": "timestamp",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "dashboard": {
            "handlers": ["file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "media_files": {
            "handlers": ["file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "registration": {
            "handlers": ["file"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "contributions": {
            "handlers": ["file", "console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": True,
        },
        "console": {
            "handlers": ["console"],
            "level": "CRITICAL",
            "propagate": True,
        },
        "celery": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "celery.task": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "celery.worker": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Bootstrap settings
BOOTSTRAP_VERSION = get_env('BOOTSTRAP_VERSION', default='5.3.2')
BOOTSTRAP_CDN_URL = f"https://cdn.jsdelivr.net/npm/bootstrap@{BOOTSTRAP_VERSION}"
BOOTSTRAP_ICONS_VERSION = get_env('BOOTSTRAP_ICONS_VERSION', default='1.1.1')
BOOTSTRAP_ICONS_URL = f"https://cdn.jsdelivr.net/npm/bootstrap-icons@{BOOTSTRAP_ICONS_VERSION}"

# Dashboard Theme Configuration
DASHBOARD_THEME = get_env('DASHBOARD_THEME', default='default')

# Cache Configuration
# Get cache backend from environment or use Redis if available
cache_backend = get_env('CACHE_BACKEND', default=None)
cache_timeout = get_env('CACHE_TIMEOUT', default=300, cast=int)
cache_location = get_env('CACHE_LOCATION', default=None)

if cache_backend:
    # Use configured backend from environment
    CACHES = {
        'default': {
            'BACKEND': cache_backend,
            'LOCATION': cache_location or 'cache',
            'TIMEOUT': cache_timeout,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
elif cache_location:
    # Use Redis if location is specified
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': cache_location,
            'TIMEOUT': cache_timeout,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }
else:
    # Default: Use Redis from Celery broker URL (same Redis instance)
    # Extract Redis URL from Celery broker
    celery_broker = get_env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')
    # Use database 1 for cache (Celery uses database 0)
    if 'redis://' in celery_broker:
        # Replace database number with 1 for cache
        cache_redis_url = celery_broker.rsplit('/', 1)[0] + '/1'
    else:
        cache_redis_url = 'redis://127.0.0.1:6379/1'
    
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': cache_redis_url,
            'TIMEOUT': cache_timeout,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }

# Celery Configuration
CELERY_BROKER_URL = get_env('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/0')
# Use django-celery-results backend to store results in database (visible in admin)
# Allow both 'django-db' (short form) and full path for backward compatibility
_result_backend = get_env('CELERY_RESULT_BACKEND', default='django-db')
if _result_backend == 'django-db':
    CELERY_RESULT_BACKEND = 'django_celery_results.backends.database:DatabaseBackend'
else:
    CELERY_RESULT_BACKEND = _result_backend

# Celery Configuration Options
CELERY_TIMEZONE = get_env('TIME_ZONE', default='Europe/Berlin')
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ROUTES = {
    # Network downloads are intentionally isolated so long Nextcloud transfers
    # cannot occupy the general-purpose worker pool. The download worker runs
    # with concurrency=1 to avoid parallel downloads over the same connection.
    'austausch.tasks.download_exchange_files': {'queue': 'download'},
    'licenses.tasks.download_nextcloud_video_file_to_storage': {'queue': 'download'},
    # CPU/FFmpeg-heavy tasks stay on the render worker pool.
    'media_files.tasks.render_video_task': {'queue': 'render'},
    'tools.tasks.analyze_audio_normalize_job': {'queue': 'render'},
    'tools.tasks.cleanup_old_audio_normalize_jobs_task': {'queue': 'render'},
    'tools.tasks.cleanup_old_projects_task': {'queue': 'render'},
    'tools.tasks.cleanup_old_video_render_operations_task': {'queue': 'render'},
    'tools.tasks.generate_slideshow': {'queue': 'render'},
    'tools.tasks.normalize_audio': {'queue': 'render'},
    # Copying planned videos is storage-heavy but should not block downloads,
    # renders, or scans. Keep it on its own serial worker.
    'media_files.tasks.copy_videos_for_plan': {'queue': 'copy'},
    # Anchor rendering is handled by an external renderer environment. Keep the
    # wait/render/poll chain away from local workers unless they explicitly
    # consume the anchor_render queue.
    'planung.tasks.anchor_render_chain': {'queue': 'anchor_render'},
    'planung.tasks.poll_anchor_render_job': {'queue': 'anchor_render'},
}
# Allow overriding time limits via environment variables
CELERY_TASK_TIME_LIMIT = get_env('CELERY_TASK_TIME_LIMIT', default=30 * 60, cast=int)  # 30 minutes default
CELERY_TASK_SOFT_TIME_LIMIT = get_env('CELERY_TASK_SOFT_TIME_LIMIT', default=25 * 60, cast=int)  # 25 minutes default
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 10
# Celery worker concurrency (number of parallel processes)
# None = auto-detect CPU cores, integer = specific number
_celery_concurrency = get_env('CELERY_WORKER_CONCURRENCY', default=None)
if _celery_concurrency and _celery_concurrency.strip():
    try:
        CELERY_WORKER_CONCURRENCY = int(_celery_concurrency)
    except (ValueError, TypeError):
        CELERY_WORKER_CONCURRENCY = None
else:
    CELERY_WORKER_CONCURRENCY = None
# Enable extended result format to store more task information
CELERY_RESULT_EXTENDED = True
CELERY_RESULT_BACKEND_ALWAYS_RETRY = True
CELERY_RESULT_BACKEND_MAX_RETRIES = 10
# Fix deprecation warning: use new broker connection retry setting
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# Fix security warning: prevent running with superuser privileges
CELERYD_FORCE_EXECV = True

# Use django-celery-beat scheduler (allows managing periodic tasks via admin)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery Beat Schedule from environment variables
# Note: Tasks can also be managed via django-celery-beat admin interface
CELERY_BEAT_SCHEDULE = {
    'expire_rentals': {
        'task': 'ok_tools.tasks.run_expire_room_rentals_task',
        'schedule': parse_crontab_env('CELERY_BEAT_EXPIRE_RENTALS', '*/30 * * * *'),
    },
    'cleanup_old_backups': {
        'task': 'ok_tools.tasks.cleanup_old_backups_task',
        'schedule': parse_crontab_env('CELERY_BEAT_CLEANUP_OLD_BACKUPS', '0 2 * * *'),
    },
    'run_backup_db': {
        'task': 'ok_tools.tasks.run_backup_db_task',
        'schedule': parse_crontab_env('CELERY_BEAT_RUN_BACKUP_DB', '0 3 * * *'),
    },
    'auto_scan': {
        'task': 'media_files.tasks.run_auto_scan',
        'schedule': parse_crontab_env('CELERY_BEAT_AUTO_SCAN', '0 */2 * * *'),
    },
    'scan_inventory_images': {
        'task': 'inventory.tasks.run_scan_inventory_images',
        'schedule': parse_crontab_env('CELERY_BEAT_SCAN_INVENTORY_IMAGES', '30 */6 * * *'),
    },
    'link_orphan_licenses': {
        'task': 'media_files.tasks.run_link_orphan_licenses',
        'schedule': parse_crontab_env('CELERY_BEAT_LINK_ORPHAN_LICENSES', '0 3 * * *'),
    },
    'sync_licenses_videos': {
        'task': 'media_files.tasks.run_sync_licenses_videos',
        'schedule': parse_crontab_env('CELERY_BEAT_SYNC_LICENSES_VIDEOS', '0 4 * * *'),
    },
    'rescan_mediathek_links_from_planung': {
        'task': 'licenses.tasks.rescan_mediathek_links_from_planung',
        'schedule': parse_crontab_env('CELERY_BEAT_RESCAN_MEDIATHEK_PLANUNG', '15 8 * * *'),
        'kwargs': {'days_back': 2, 'days_forward': 0},
    },
    'rescan_mediathek_links_from_contributions': {
        'task': 'licenses.tasks.rescan_mediathek_links_from_contributions',
        'schedule': parse_crontab_env('CELERY_BEAT_RESCAN_MEDIATHEK_CONTRIBUTIONS', '45 8 * * *'),
        'kwargs': {'days_back': 14, 'days_forward': 0},
    },
    'update_video_metadata': {
        'task': 'media_files.tasks.run_update_video_metadata',
        'schedule': parse_crontab_env('CELERY_BEAT_UPDATE_VIDEO_METADATA', '0 1 1 * *'),
        'kwargs': {'missing_only': True},
    },
    'cleanup_old_file_operations': {
        'task': 'media_files.tasks.run_cleanup_old_file_operations',
        'schedule': parse_crontab_env('CELERY_BEAT_CLEANUP_OLD_FILE_OPERATIONS', '0 1 * * 0'),
        'kwargs': {'older_than_days': 30, 'keep_failed': True},
    },
    'cleanup_missing_files': {
        'task': 'media_files.tasks.run_cleanup_missing_files',
        'schedule': parse_crontab_env('CELERY_BEAT_CLEANUP_MISSING_FILES', '0 5 * * 0'),
        'kwargs': {'all_storages': True},
    },
    'cleanup_deleted_nextcloud_videos': {
        'task': 'ok_tools.tasks.run_cleanup_deleted_nextcloud_videos_task',
        'schedule': parse_crontab_env('CELERY_BEAT_CLEANUP_DELETED_NEXTCLOUD_VIDEOS', '0 2 * * *'),
    },
    'cleanup_signing_sessions': {
        'task': 'ok_tools.tasks.run_cleanup_signing_sessions_task',
        'schedule': parse_crontab_env('CELERY_BEAT_CLEANUP_SIGNING_SESSIONS', '30 2 * * *'),
    },
    'sync_exchange_folders': {
        'task': 'austausch.tasks.sync_exchange_folders',
        'schedule': parse_crontab_env('CELERY_BEAT_SYNC_EXCHANGE', '0 2 * * *'),
    },
    'send_return_reminders': {
        'task': 'ok_tools.tasks.send_return_reminders_task',
        'schedule': parse_crontab_env('CELERY_BEAT_SEND_RETURN_REMINDERS', '0 * * * *'),
    },
    'cleanup_old_tool_projects': {
        'task': 'tools.tasks.cleanup_old_projects_task',
        'schedule': parse_crontab_env('CELERY_BEAT_CLEANUP_TOOL_PROJECTS', '0 4 * * 0'),
        'kwargs': {'older_than_days': 30},
    },
    'cleanup_old_audio_normalize_jobs': {
        'task': 'tools.tasks.cleanup_old_audio_normalize_jobs_task',
        'schedule': parse_crontab_env('CELERY_BEAT_CLEANUP_AUDIO_NORMALIZE_JOBS', '0 4 * * 0'),
        'kwargs': {'older_than_days': 30, 'delete_if_missing_files': True},
    },
    'cleanup_old_video_render_operations': {
        'task': 'tools.tasks.cleanup_old_video_render_operations_task',
        'schedule': parse_crontab_env('CELERY_BEAT_CLEANUP_VIDEO_RENDER_OPERATIONS', '0 4 * * 0'),
        'kwargs': {'older_than_days': 30, 'keep_failed': True},
    },
}
