# Generated by Django 5.2.7 on 2026-01-07 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0014_change_created_at_to_i18n'),
        ('media_files', '0015_alter_videofile_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextcloud_base_url', models.URLField(help_text='Base URL of Nextcloud server (e.g., https://cloud.example.com)', verbose_name='Nextcloud Base URL')),
                ('nextcloud_username', models.CharField(help_text='Service account username for WebDAV access', max_length=255, verbose_name='Nextcloud Username')),
                ('nextcloud_password', models.CharField(help_text='App password or service account password', max_length=255, verbose_name='Nextcloud Password')),
                ('channel_folder_pattern', models.CharField(default='{channel}', help_text='Pattern for channel folders: {channel} will be replaced', max_length=255, verbose_name='Channel Folder Pattern')),
                ('exchange_folder_pattern', models.CharField(default='{channel}_austausch', help_text='Pattern for exchange folders: {channel} will be replaced', max_length=255, verbose_name='Exchange Folder Pattern')),
                ('sync_schedule', models.CharField(default='0 2 * * *', help_text='Cron schedule for sync task (e.g., "0 2 * * *" for daily at 2 AM)', max_length=255, verbose_name='Sync Schedule')),
                ('sync_lookback_days', models.IntegerField(default=7, help_text='How many days back to check for new items', verbose_name='Sync Lookback Days')),
                ('download_storage_path', models.CharField(help_text='Local path for downloaded files before import', max_length=500, verbose_name='Download Storage Path')),
                ('auto_import_enabled', models.BooleanField(default=False, help_text='Automatically enqueue PeerTube upload after import', verbose_name='Auto-Import Enabled')),
                ('channels_list', models.TextField(blank=True, help_text='Comma-separated list of channel names to sync (optional, can be auto-discovered)', verbose_name='Channels List')),
            ],
            options={
                'verbose_name': 'Exchange Configuration',
                'verbose_name_plural': 'Exchange Configuration',
            },
        ),
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_id', models.IntegerField(blank=True, db_index=True, help_text='Numeric ID from filename (if OK-Tools managed)', null=True, verbose_name='Contribution ID')),
                ('filename', models.CharField(max_length=500, verbose_name='Filename')),
                ('file_path', models.CharField(help_text='Full Nextcloud path', max_length=1000, verbose_name='File Path')),
                ('channel', models.CharField(help_text='Source channel name', max_length=100, verbose_name='Channel')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('file_type', models.CharField(help_text="'video' or 'pdf'", max_length=50, verbose_name='File Type')),
                ('checksum', models.CharField(blank=True, help_text='SHA256 checksum', max_length=64, verbose_name='Checksum')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('sendeverantwortung', models.CharField(blank=True, max_length=255, verbose_name='Sender Responsible')),
                ('is_oktools_managed', models.BooleanField(default=False, help_text='Item is managed by OK-Tools (has contribution_id)', verbose_name='OK-Tools Managed')),
                ('is_legacy', models.BooleanField(default=False, help_text='Item without numeric ID prefix', verbose_name='Legacy')),
                ('import_status', models.CharField(choices=[('new', 'New'), ('imported', 'Imported'), ('failed', 'Failed')], db_index=True, default='new', max_length=20, verbose_name='Import Status')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Discovered At')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Last Seen At')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Imported At')),
                ('imported_license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_items', to='licenses.license', verbose_name='Imported License')),
            ],
            options={
                'verbose_name': 'Exchange Item',
                'verbose_name_plural': 'Exchange Items',
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Imported By')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_import_records', to='licenses.license', verbose_name='License')),
                ('video_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_imports', to='media_files.videofile', verbose_name='Video File')),
                ('exchange_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='austausch.exchangeitem', verbose_name='Exchange Item')),
            ],
            options={
                'verbose_name': 'Exchange Import',
                'verbose_name_plural': 'Exchange Imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='exchangeitem',
            index=models.Index(fields=['contribution_id'], name='austausch_e_contrib_23f8df_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeitem',
            index=models.Index(fields=['channel', 'discovered_at'], name='austausch_e_channel_87adc7_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeitem',
            index=models.Index(fields=['import_status'], name='austausch_e_import__0dc331_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangeitem',
            unique_together={('file_path', 'channel')},
        ),
    ]
