# Generated by Django 5.2.7 on 2026-01-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('austausch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeconfig',
            name='sync_date_folders_days',
            field=models.IntegerField(default=2, help_text='How many recent date folders to scan (e.g., 2 = today and yesterday)', verbose_name='Sync Date Folders Days'),
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='sync_lookback_days',
            field=models.IntegerField(default=7, help_text='How many days back to check for new items (for file age filtering)', verbose_name='Sync Lookback Days'),
        ),
    ]
