# Generated by Django 5.2.7 on 2026-01-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('austausch', '0002_exchangeconfig_sync_date_folders_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeitem',
            name='pdf_path',
            field=models.CharField(blank=True, help_text='Full Nextcloud path to PDF file (if part of package)', max_length=1000, verbose_name='PDF Path'),
        ),
        migrations.AlterField(
            model_name='exchangeitem',
            name='file_path',
            field=models.CharField(help_text='Full Nextcloud path to video file', max_length=1000, verbose_name='File Path'),
        ),
    ]
