# Generated by Django 5.2.7 on 2026-01-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('austausch', '0003_exchangeitem_pdf_path_alter_exchangeitem_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeitem',
            name='thumbnail_path',
            field=models.CharField(blank=True, help_text='Full Nextcloud path to thumbnail image (jpg, png, etc.)', max_length=1000, verbose_name='Thumbnail Path'),
        ),
    ]
