# Generated by Django 5.2.7 on 2026-01-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('austausch', '0004_exchangeitem_thumbnail_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeimport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_download', 'Pending Download'), ('downloading', 'Downloading'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
