# Generated by Django 5.2.7 on 2026-01-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('austausch', '0005_alter_exchangeimport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeconfig',
            name='sync_schedule',
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='sync_date_folders_days',
            field=models.IntegerField(default=2, help_text='How many recent date folders to scan (e.g., 2 = today and yesterday). Files are organized in date-named folders like "2026_01_07".', verbose_name='Sync Date Folders Days'),
        ),
        migrations.AlterField(
            model_name='exchangeconfig',
            name='sync_lookback_days',
            field=models.IntegerField(default=7, help_text='How many days back to check for new items (for file age filtering). Only files modified within this period will be processed.', verbose_name='Sync Lookback Days'),
        ),
    ]
