# Generated by Django 5.2.7 on 2026-01-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('austausch', '0007_add_storage_location_to_exchange_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeconfig',
            name='download_storage_path',
            field=models.CharField(blank=True, help_text='Local path for downloaded files before import (used if storage location is not set)', max_length=500, verbose_name='Download Storage Path'),
        ),
    ]
