# Generated by Django 5.2.7 on 2026-01-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('austausch', '0011_exporttoserverrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeconfig',
            name='local_pdf_fallback_path',
            field=models.CharField(blank=True, help_text='First local directory for unsigned licenses; PDFs searched by pattern {number}_*.pdf.', max_length=500, verbose_name='Local PDF Fallback Path'),
        ),
    ]
