# Generated by Django 4.0.5 on 2022-08-02 09:31

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion
import licenses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(
                    max_length=255, null=True, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('subtitle', models.CharField(blank=True,
                 max_length=255, null=True, verbose_name='subtitle')),
                ('description', models.TextField(verbose_name='description')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('date', models.DateTimeField(blank=True,
                 null=True, verbose_name='broadcast date')),
                ('repetitions_allowed', models.BooleanField(
                    verbose_name='repetitions allowed')),
                ('media_authority_exchange_allowed', models.BooleanField(
                    verbose_name='Media Authority exchange allowed')),
                ('youth_protection_necessary', models.BooleanField(
                    verbose_name='Youth protection necessary')),
                ('store_in_ok_media_library', models.BooleanField(
                    verbose_name='Stor in OK media library')),
                ('category', models.ForeignKey(default=licenses.models.default_category,
                 on_delete=django.db.models.deletion.CASCADE, to='licenses.category')),
                ('okuser', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
