# Generated by Django 4.0.5 on 2022-08-02 11:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='date',
        ),
        migrations.AddField(
            model_name='license',
            name='suggested_date',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='suggested broadcast date'),
        ),
        migrations.AlterField(
            model_name='license',
            name='store_in_ok_media_library',
            field=models.BooleanField(
                verbose_name='Store in OK media library'),
        ),
    ]
