# Generated by Django 4.1.7 on 2024-02-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('licenses', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.profile', verbose_name='Profile'),
        ),
    ]
