# Generated by Django 4.0.5 on 2022-10-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'License',
                     'verbose_name_plural': 'Licenses'},
        ),
    ]
