# Generated by Django 4.1.7 on 2025-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_license_youth_protection_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='infoblock',
            field=models.BooleanField(default=False, verbose_name='Infoblock'),
        ),
    ]
