# Generated by Django 5.2.5 on 2025-10-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_license_infoblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Maximum 4 tags', null=True, verbose_name='Tags'),
        ),
    ]
