# Generated by Django 4.0.5 on 2022-08-16 11:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_rename_category_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='licensetemplate',
            name='further_persons',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Further persons'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='licensetemplate',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='licensetemplate',
            name='duration',
            field=models.DurationField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='licensetemplate',
            name='repetitions_allowed',
            field=models.BooleanField(verbose_name='Repetitions allowed'),
        ),
        migrations.AlterField(
            model_name='licensetemplate',
            name='subtitle',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='licensetemplate',
            name='suggested_date',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='Suggested broadcast date'),
        ),
        migrations.AlterField(
            model_name='licensetemplate',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
