# Generated by Django 4.0.5 on 2022-09-13 13:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_alter_licensetemplate_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                max_length=255, unique=True, verbose_name='Category'),
        ),
    ]
