# Generated by Django 4.0.5 on 2022-08-15 09:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_rename_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserequest',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmed'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                max_length=255, null=True, verbose_name='Category'),
        ),
    ]
