# Generated by Django 4.1.3 on 2023-03-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_alter_license_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
