# Generated by Django 4.0.5 on 2022-08-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_alter_category_options_and_more'),
        ('licenses', '0005_licenserequest_confirmed_alter_category_name'),
    ]

    operations = [
    ]
