# Generated by Django 5.2.5 on 2025-10-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_license_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='tags',
            field=models.JSONField(blank=True, default=None, help_text='Maximum 4 tags', null=True, verbose_name='Tags'),
        ),
    ]
