# Generated by Django 4.0.5 on 2022-08-17 07:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_merge_20220816_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category',
                     'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='licenserequest',
            options={'verbose_name': 'License Request',
                     'verbose_name_plural': 'License Requests'},
        ),
        migrations.AlterModelOptions(
            name='licensetemplate',
            options={'verbose_name': 'License Template',
                     'verbose_name_plural': 'License Templates'},
        ),
        migrations.AlterField(
            model_name='licensetemplate',
            name='further_persons',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Further involved persons'),
        ),
    ]
