# Generated by Django 5.2.5 on 2025-10-10 20:51

from django.db import migrations


def update_empty_tags_to_none(apps, schema_editor):
    """
    Update all licenses with empty tags lists [] to None.
    
    This migration fixes the issue where existing licenses show "[]" 
    in the admin interface instead of an empty field.
    """
    License = apps.get_model('licenses', 'License')
    
    # Find all licenses with empty tags lists
    licenses_with_empty_tags = License.objects.filter(tags=[])
    
    # Update them to None
    updated_count = licenses_with_empty_tags.update(tags=None)
    
    print(f"Updated {updated_count} licenses to set tags=None")


def reverse_update_empty_tags_to_none(apps, schema_editor):
    """
    Reverse migration - convert None back to empty list.
    
    Note: This is not recommended as it brings back the "[]" display issue.
    """
    License = apps.get_model('licenses', 'License')
    
    # Find all licenses with None tags
    licenses_with_none_tags = License.objects.filter(tags__isnull=True)
    
    # Update them to empty list
    updated_count = licenses_with_none_tags.update(tags=[])
    
    print(f"Updated {updated_count} licenses to set tags=[]")


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_change_tags_default'),
    ]

    operations = [
        migrations.RunPython(
            update_empty_tags_to_none,
            reverse_update_empty_tags_to_none,
        ),
    ]
