# Generated by Django 4.0.5 on 2022-08-23 06:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0009_licenserequest_is_screen_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserequest',
            name='number',
            field=models.IntegerField(
                default=1, unique=True, verbose_name='Number'),
        ),
    ]
