# Generated by Django 5.2.7 on 2025-11-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0008_alter_license_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image', null=True, verbose_name='Signature'),
        ),
    ]
