# Generated by Django 4.0.5 on 2022-08-23 09:51

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0008_licensetemplate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserequest',
            name='is_screen_board',
            field=models.BooleanField(
                default=False, verbose_name='Screen Board'),
        ),
    ]
