# Generated by Django 5.2.7 on 2025-11-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0009_license_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_live',
            field=models.BooleanField(default=False, help_text='Live broadcasts do not allow repetitions, exchange, or mediathek storage.', verbose_name='Live broadcast'),
        ),
    ]
