# Generated by Django 4.0.5 on 2022-08-23 12:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0009_licenserequest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetemplate',
            name='duration',
            field=models.DurationField(blank=True, verbose_name='Duration'),
        ),
    ]
