# Generated by Django 4.0.5 on 2022-08-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0009_licenserequest_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenserequest',
            name='number',
        ),
    ]
