# Generated by Django 4.1 on 2022-08-24 11:59

from django.db import migrations
from django.db import models
import datetime
import django.db.models.deletion
import licenses.models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0011_licenserequest_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenserequest",
            name="category",
            field=models.ForeignKey(
                default=licenses.models.default_category,
                on_delete=django.db.models.deletion.CASCADE,
                to="licenses.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="licensetemplate",
            name="duration",
            field=models.DurationField(
                blank=True,
                default=datetime.timedelta(0),
                help_text="Format: hh:mm:ss",
                verbose_name="Duration",
            ),
        ),
    ]
