# Generated by Django 4.0.5 on 2022-09-07 09:06

from django.db import migrations
from django.db import models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0012_alter_licenserequest_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetemplate',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(
                0), help_text='Format: hh:mm:ss or mm:ss', verbose_name='Duration'),
        ),
    ]
