# Generated by Django 5.2.7 on 2025-12-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0012_add_numeric_id_to_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Erstellt am'),
        ),
    ]
