# Generated by Django 4.0.5 on 2022-08-29 07:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0012_alter_licenserequest_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name='Category'),
        ),
    ]
