# Generated by Django 5.2.7 on 2025-12-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0013_change_created_at_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
    ]
