# Generated by Django 5.2.7 on 2026-01-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0014_change_created_at_to_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_board_duration', models.IntegerField(default=20, help_text='Fixed duration for screen board display in seconds', verbose_name='Screen Board Duration (seconds)')),
            ],
            options={
                'verbose_name': 'Licenses Configuration',
                'verbose_name_plural': 'Licenses Configuration',
            },
        ),
    ]
