# Generated by Django 5.2.7 on 2026-01-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0015_licensesconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensesconfig',
            name='download_storage_path',
            field=models.CharField(default='/app/media/', help_text='Local path for downloaded files', max_length=500, verbose_name='Download Storage Path'),
        ),
    ]

