# Generated by Django 6.0.6 on 2026-06-21 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0024_license_mediathek_url_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the license was confirmed (Genehmigt).', null=True, verbose_name='Confirmed at'),
        ),
        migrations.AddField(
            model_name='licensesconfig',
            name='freistellung_city',
            field=models.CharField(blank=True, default='', help_text='City name for "Ort, Datum" in the Freistellung print form.', max_length=255, verbose_name='Freistellung city'),
        ),
        migrations.AddField(
            model_name='licensesconfig',
            name='freistellung_enabled',
            field=models.BooleanField(default=False, help_text='Enable freistellung-specific text overlays and staff signature in the generated PDF.', verbose_name='Freistellung enabled'),
        ),
        migrations.AddField(
            model_name='licensesconfig',
            name='freistellung_sendezeit_no_protection',
            field=models.CharField(blank=True, default='Sendezeit gem. JMStV zu beachten: Nein', help_text='Text for "Sendezeit gem. JMStV zu beachten" when no youth protection is needed.', max_length=500, verbose_name='Sendezeit text (no youth protection)'),
        ),
        migrations.AddField(
            model_name='licensesconfig',
            name='freistellung_sendezeit_with_protection',
            field=models.CharField(blank=True, default='Sendezeit gem. JMStV zu beachten: Ja\nSendezeit ab 22:00 Uhr', help_text='Text for "Sendezeit gem. JMStV zu beachten" and "Sendezeit ab" when youth protection is needed. Use \\n for line break.', max_length=500, verbose_name='Sendezeit text (with youth protection)'),
        ),
        migrations.AddField(
            model_name='licensesconfig',
            name='freistellung_signature_text',
            field=models.CharField(blank=True, default='Im Auftrag des Vorstands der Medienanstalt Sachsen-Anhalt', help_text='Text below the signature on the Freistellung print form.', max_length=500, verbose_name='Freistellung signature text'),
        ),
        migrations.AddField(
            model_name='licensesconfig',
            name='freistellung_signature_user',
            field=models.ForeignKey(blank=True, help_text='Staff member whose signature appears on the Freistellung print form. When this user confirms a license, their signature is added to the PDF.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Freistellung signature user'),
        ),
        migrations.AlterField(
            model_name='licensenotificationevent',
            name='event_type',
            field=models.CharField(choices=[('video_uploaded', 'Video uploaded'), ('draft_scheduled', 'Draft scheduled'), ('planned_scheduled', 'Planned scheduled'), ('contributions_available', 'Contributions available'), ('mediathek_published', 'Mediathek published')], db_index=True, max_length=64, verbose_name='Event type'),
        ),
    ]
