# Generated by Django 6.0.6 on 2026-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0026_license_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensesconfig',
            name='freistellung_sendezeit_time',
            field=models.CharField(blank=True, default='22:00', help_text='Time for "Sendezeit ab ___ Uhr" in the Freistellung print form (e.g. 22:00).', max_length=20, verbose_name='Sendezeit time'),
        ),
    ]
