# Generated by Django 6.0.6 on 2026-08-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0027_licensesconfig_freistellung_sendezeit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensesconfig',
            name='auto_download_to_storage',
            field=models.BooleanField(default=True, help_text='Download a file to local storage as soon as it was uploaded to Nextcloud, without pressing "Download" in the admin. Requires a configured download storage path and a running Celery worker on the "download" queue.', verbose_name='Download Nextcloud files automatically'),
        ),
        migrations.AddField(
            model_name='nextcloudvideofile',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, help_text='When the file was downloaded from Nextcloud to local storage', null=True, verbose_name='Downloaded at'),
        ),
        migrations.AddField(
            model_name='nextcloudvideofile',
            name='local_path',
            field=models.CharField(blank=True, default='', help_text='Path of the downloaded copy in local storage', max_length=1000, verbose_name='Local path'),
        ),
    ]
