# Generated by Django 6.0.6 on 2026-08-20 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0029_mark_existing_nextcloud_files_as_downloaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouthProtectionWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('none', 'not necessary'), ('from_12', 'from 12'), ('from_16', 'from 16'), ('from_18', 'from 18')], max_length=255, unique=True, verbose_name='Youth protection category')),
                ('enabled', models.BooleanField(default=True, help_text='When off, this category may be planned at any time.', verbose_name='Enforce this window')),
                ('start_time', models.TimeField(default=datetime.time(22, 0), verbose_name='Broadcast allowed from')),
                ('end_time', models.TimeField(default=datetime.time(6, 0), help_text='Earlier than the start time means the window crosses midnight, e.g. 22:00-06:00.', verbose_name='Broadcast allowed until')),
            ],
            options={
                'verbose_name': 'Youth protection broadcast window',
                'verbose_name_plural': 'Youth protection broadcast windows',
                'ordering': ['category'],
            },
        ),
    ]
