# Generated by Django 5.2.7 on 2026-01-15 21:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import tools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_path', models.CharField(help_text='Base path for storing uploaded media files', max_length=500, verbose_name='Storage Path')),
                ('output_path', models.CharField(help_text='Base path for storing generated videos', max_length=500, verbose_name='Output Path')),
                ('max_upload_size', models.IntegerField(default=500, help_text='Maximum file upload size in megabytes', verbose_name='Max Upload Size (MB)')),
                ('allowed_image_formats', models.CharField(default='jpg,jpeg,png', help_text='Comma-separated list of allowed image extensions', max_length=100, verbose_name='Allowed Image Formats')),
                ('allowed_video_formats', models.CharField(default='mp4,mov,avi,mkv,webm,flv,wmv,m4v', help_text='Comma-separated list of allowed video extensions', max_length=200, verbose_name='Allowed Video Formats')),
                ('allowed_audio_formats', models.CharField(default='mp3,wav,m4a,flac,ogg', help_text='Comma-separated list of allowed audio extensions', max_length=100, verbose_name='Allowed Audio Formats')),
                ('ffmpeg_path', models.CharField(default='ffmpeg', help_text='Path to ffmpeg executable', max_length=500, verbose_name='FFmpeg Path')),
                ('ffprobe_path', models.CharField(default='ffprobe', help_text='Path to ffprobe executable', max_length=500, verbose_name='FFprobe Path')),
            ],
            options={
                'verbose_name': 'Tools Configuration',
                'verbose_name_plural': 'Tools Configuration',
            },
        ),
        migrations.CreateModel(
            name='SlideshowProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the slideshow project', max_length=255, verbose_name='Project Name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('slide_duration', models.FloatField(default=20.0, help_text='Duration of each slide in seconds', verbose_name='Slide Duration (seconds)')),
                ('fps', models.IntegerField(default=25, help_text='Frames per second', verbose_name='FPS')),
                ('width', models.IntegerField(default=1920, help_text='Video width in pixels', verbose_name='Width')),
                ('height', models.IntegerField(default=1080, help_text='Video height in pixels', verbose_name='Height')),
                ('use_transitions', models.BooleanField(default=True, help_text='Enable transitions between slides', verbose_name='Use Transitions')),
                ('transition_type', models.CharField(choices=[('fade', 'Fade'), ('fadeblack', 'Fade to Black'), ('fadewhite', 'Fade to White'), ('wipeleft', 'Wipe Left'), ('wiperight', 'Wipe Right'), ('wipeup', 'Wipe Up'), ('wipedown', 'Wipe Down'), ('slideleft', 'Slide Left'), ('slideright', 'Slide Right'), ('slideup', 'Slide Up'), ('slidedown', 'Slide Down'), ('smoothleft', 'Smooth Left'), ('smoothright', 'Smooth Right'), ('circleopen', 'Circle Open'), ('circleclose', 'Circle Close'), ('radial', 'Radial'), ('random', 'Random')], default='random', max_length=20, verbose_name='Transition Type')),
                ('transition_duration', models.FloatField(default=2.0, help_text='Duration of transitions in seconds', verbose_name='Transition Duration (seconds)')),
                ('video_bitrate', models.CharField(default='5M', help_text='Video bitrate (e.g., 5M, 10M)', max_length=20, verbose_name='Video Bitrate')),
                ('audio_bitrate', models.CharField(default='256k', help_text='Audio bitrate (e.g., 128k, 256k)', max_length=20, verbose_name='Audio Bitrate')),
                ('video_codec', models.CharField(blank=True, help_text='Video codec (auto-detect if empty)', max_length=50, verbose_name='Video Codec')),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('output_file', models.FileField(blank=True, null=True, upload_to=tools.models.slideshow_output_path, verbose_name='Output Video File')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slideshow_projects', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Slideshow Project',
                'verbose_name_plural': 'Slideshow Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlideshowMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tools.models.slideshow_media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mov', 'avi', 'mkv', 'webm', 'flv', 'wmv', 'm4v'])], verbose_name='Media File')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10, verbose_name='Media Type')),
                ('order', models.IntegerField(default=0, help_text='Order in slideshow sequence', verbose_name='Order')),
                ('duration_override', models.FloatField(blank=True, help_text='Override default slide duration for this file', null=True, verbose_name='Duration Override (seconds)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='tools.slideshowproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Slideshow Media',
                'verbose_name_plural': 'Slideshow Media',
                'ordering': ['project', 'order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SlideshowAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tools.models.slideshow_audio_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'm4a', 'flac', 'ogg'])], verbose_name='Audio File')),
                ('name', models.CharField(help_text='Name of the audio track', max_length=255, verbose_name='Name')),
                ('duration', models.FloatField(blank=True, help_text='Duration of audio in seconds', null=True, verbose_name='Duration (seconds)')),
                ('is_library', models.BooleanField(default=False, help_text='Is this a library audio file available to all projects?', verbose_name='Library File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('project', models.ForeignKey(blank=True, help_text='Project this audio belongs to (null for library files)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='tools.slideshowproject', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Slideshow Audio',
                'verbose_name_plural': 'Slideshow Audio',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='slideshowproject',
            index=models.Index(fields=['created_by', 'status'], name='tools_slide_created_123abc_idx'),
        ),
        migrations.AddIndex(
            model_name='slideshowproject',
            index=models.Index(fields=['status', 'created_at'], name='tools_slide_status_456def_idx'),
        ),
        migrations.AddIndex(
            model_name='slideshowmedia',
            index=models.Index(fields=['project', 'order'], name='tools_slide_project_789ghi_idx'),
        ),
        migrations.AddIndex(
            model_name='slideshowaudio',
            index=models.Index(fields=['project', 'is_library'], name='tools_slide_project_012jkl_idx'),
        ),
    ]
