# Generated by Django 5.2.7 on 2026-01-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_add_media_library_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='slideshowaudio',
            new_name='tools_slide_project_cbcb65_idx',
            old_name='tools_slide_project_012jkl_idx',
        ),
        migrations.RenameIndex(
            model_name='slideshowmedia',
            new_name='tools_slide_project_1aa7e9_idx',
            old_name='tools_slide_project_789ghi_idx',
        ),
        migrations.RenameIndex(
            model_name='slideshowmedia',
            new_name='tools_slide_is_libr_d5b862_idx',
            old_name='tools_slide_is_libr_345mno_idx',
        ),
        migrations.RenameIndex(
            model_name='slideshowproject',
            new_name='tools_slide_created_367d24_idx',
            old_name='tools_slide_created_123abc_idx',
        ),
        migrations.RenameIndex(
            model_name='slideshowproject',
            new_name='tools_slide_status_14c7c3_idx',
            old_name='tools_slide_status_456def_idx',
        ),
    ]
