# Generated by Django 5.2.7 on 2026-01-18 00:00

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
import tools.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_rename_tools_slide_project_012jkl_idx_tools_slide_project_cbcb65_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsconfig',
            name='audio_normalize_default_bitrate',
            field=models.CharField(default='192k', help_text='Default audio bitrate for normalized files (e.g., 192k)', max_length=20, verbose_name='Audio Normalize Default Bitrate'),
        ),
        migrations.AddField(
            model_name='toolsconfig',
            name='audio_normalize_default_preset',
            field=models.CharField(default='tv_natural', help_text='Default audio normalize preset ID', max_length=50, verbose_name='Audio Normalize Default Preset'),
        ),
        migrations.AddField(
            model_name='toolsconfig',
            name='audio_normalize_input_path',
            field=models.CharField(default='', help_text='Base path for audio normalize source files (optional)', max_length=500, verbose_name='Audio Normalize Input Path'),
        ),
        migrations.AddField(
            model_name='toolsconfig',
            name='audio_normalize_output_path',
            field=models.CharField(default='', help_text='Base path for audio normalize output files (optional)', max_length=500, verbose_name='Audio Normalize Output Path'),
        ),
        migrations.CreateModel(
            name='AudioNormalizeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('preset_id', models.CharField(default='tv_natural', help_text='Audio normalize preset ID', max_length=50, verbose_name='Preset')),
                ('target', models.CharField(choices=[('tv', 'TV (R128)'), ('web', 'Web')], default='tv', help_text='Target loudness profile', max_length=10, verbose_name='Target')),
                ('input_file', models.FileField(upload_to=tools.models.audio_normalize_input_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'mkv', 'avi', 'webm', 'm4v', 'mp3', 'wav', 'm4a', 'flac', 'ogg'])], verbose_name='Input File')),
                ('output_file', models.FileField(blank=True, null=True, upload_to=tools.models.audio_normalize_output_upload_path, verbose_name='Output File')),
                ('output_filename', models.CharField(blank=True, help_text='If empty, will default to <input>_R128.mp4', max_length=255, verbose_name='Output Filename')),
                ('audio_bitrate', models.CharField(choices=[('192k', '192 kbps'), ('256k', '256 kbps')], default='192k', max_length=20, verbose_name='Audio Bitrate')),
                ('sample_rate', models.IntegerField(default=48000, verbose_name='Sample Rate')),
                ('force_stereo', models.BooleanField(default=False, help_text='If enabled, audio will be forced to 2 channels', verbose_name='Force Stereo')),
                ('input_metadata', models.JSONField(blank=True, help_text='ffprobe JSON output', null=True, verbose_name='Input Metadata')),
                ('analysis_before', models.JSONField(blank=True, help_text='loudnorm analysis JSON from pass 1', null=True, verbose_name='Analysis Before')),
                ('analysis_after', models.JSONField(blank=True, help_text='loudnorm analysis JSON from after-processing verification pass', null=True, verbose_name='Analysis After')),
                ('progress', models.IntegerField(default=0, help_text='Processing progress 0..100', verbose_name='Progress (%)')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('ffmpeg_log', models.TextField(blank=True, verbose_name='FFmpeg Log')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_normalize_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Audio Normalize Job',
                'verbose_name_plural': 'Audio Normalize Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='audionormalizejob',
            index=models.Index(fields=['created_by', 'status'], name='tools_audio_created_7c0c12_idx'),
        ),
        migrations.AddIndex(
            model_name='audionormalizejob',
            index=models.Index(fields=['status', 'created_at'], name='tools_audio_status_98c4e3_idx'),
        ),
    ]

