# Generated by Cursor on 2026-01-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_content_types_to_tools(apps, schema_editor):
    """
    Move ContentType rows from media_files -> tools for preset models.

    We keep the same PKs to preserve permissions and references.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(
        app_label="media_files",
        model__in=["videopreset", "presetoverlay", "videoencodepreset"],
    ).update(app_label="tools")


def move_content_types_back_to_media_files(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(
        app_label="tools",
        model__in=["videopreset", "presetoverlay", "videoencodepreset"],
    ).update(app_label="media_files")


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0004_audio_normalize_job_and_config"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="VideoPreset",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(help_text='Unique name for this preset (e.g., "my_custom_lower_third")', max_length=255, unique=True, verbose_name="Preset Name")),
                        ("display_name", models.CharField(help_text="Human-readable name shown in UI", max_length=255, verbose_name="Display Name")),
                        ("description", models.TextField(blank=True, help_text="Optional description of this preset", verbose_name="Description")),
                        ("is_template", models.BooleanField(default=False, help_text="If true, this preset serves as a starting template for new presets", verbose_name="Is Template")),
                        ("segment_duration", models.FloatField(default=5.0, help_text="Duration for intro/outro overlay segments", verbose_name="Segment Duration (seconds)")),
                        ("intro_clip_path", models.CharField(blank=True, help_text="Optional path to intro video clip", max_length=500, verbose_name="Intro Clip Path")),
                        ("outro_clip_path", models.CharField(blank=True, help_text="Optional path to outro video clip", max_length=500, verbose_name="Outro Clip Path")),
                        ("is_public", models.BooleanField(default=False, help_text="If true, this preset is available to all users", verbose_name="Public")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("based_on", models.ForeignKey(blank=True, help_text="Original preset this was copied from", null=True, on_delete=django.db.models.deletion.SET_NULL, to="tools.videopreset", verbose_name="Based On")),
                        ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_presets", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                    ],
                    options={
                        "verbose_name": "Video Preset",
                        "verbose_name_plural": "Video Presets",
                        "ordering": ["display_name"],
                        "db_table": "media_files_videopreset",
                    },
                ),
                migrations.CreateModel(
                    name="PresetOverlay",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("overlay_type", models.CharField(choices=[("text", "Text"), ("image", "Image")], default="text", max_length=20, verbose_name="Type")),
                        ("segment", models.CharField(choices=[("intro", "Intro"), ("outro", "Outro")], default="intro", help_text="Apply this overlay to intro or outro segment", max_length=10, verbose_name="Segment")),
                        ("order", models.IntegerField(default=0, help_text="Rendering order (lower number = rendered first/bottom layer)", verbose_name="Order")),
                        ("text_template", models.TextField(blank=True, help_text="Template with variables like {license.title}, {profile.display}", verbose_name="Text Template")),
                        ("image_path", models.CharField(blank=True, help_text="Path to image file (relative to assets/ or absolute)", max_length=500, verbose_name="Image Path")),
                        ("image_width", models.IntegerField(blank=True, null=True, verbose_name="Image Width")),
                        ("image_height", models.IntegerField(blank=True, null=True, verbose_name="Image Height")),
                        ("position_preset", models.CharField(choices=[("custom", "Custom"), ("center", "Center"), ("top_left", "Top Left"), ("top_center", "Top Center"), ("top_right", "Top Right"), ("bottom_left", "Bottom Left"), ("bottom_center", "Bottom Center"), ("bottom_right", "Bottom Right"), ("lower_third_left", "Lower Third Left"), ("lower_third_right", "Lower Third Right")], default="custom", max_length=30, verbose_name="Position Preset")),
                        ("x_position", models.CharField(default="(w-text_w)/2", help_text='X coordinate or expression (e.g., "(w-text_w)/2", "40")', max_length=100, verbose_name="X Position")),
                        ("y_position", models.CharField(default="(h-text_h)/2", help_text='Y coordinate or expression (e.g., "h-140", "(h-text_h)/2")', max_length=100, verbose_name="Y Position")),
                        ("start_time", models.FloatField(default=0.0, help_text="When to show this overlay (relative to segment start)", verbose_name="Start Time (seconds)")),
                        ("end_time", models.FloatField(default=5.0, help_text="When to hide this overlay (relative to segment start)", verbose_name="End Time (seconds)")),
                        ("animation", models.CharField(choices=[("none", "None"), ("fade", "Fade"), ("slide_up", "Slide Up"), ("slide_left", "Slide Left"), ("slide_right", "Slide Right"), ("slide_down", "Slide Down")], default="fade", max_length=20, verbose_name="Animation")),
                        ("fade_in_duration", models.FloatField(default=0.4, verbose_name="Fade In Duration (seconds)")),
                        ("fade_out_duration", models.FloatField(default=0.4, verbose_name="Fade Out Duration (seconds)")),
                        ("font_file", models.CharField(default="fonts/Roboto-Regular.ttf", help_text='Path relative to assets/ (e.g., "fonts/Roboto-Bold.ttf")', max_length=500, verbose_name="Font File")),
                        ("font_size", models.IntegerField(default=48, verbose_name="Font Size")),
                        ("font_color", models.CharField(default="white", help_text='Color name or hex (e.g., "white", "#FFFFFF")', max_length=50, verbose_name="Font Color")),
                        ("has_box", models.BooleanField(default=False, verbose_name="Has Background Box")),
                        ("box_color", models.CharField(default="black@0.5", help_text='Color with opacity (e.g., "black@0.5")', max_length=50, verbose_name="Box Color")),
                        ("box_border_width", models.IntegerField(default=12, verbose_name="Box Border Width")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("preset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="overlays", to="tools.videopreset", verbose_name="Preset")),
                    ],
                    options={
                        "verbose_name": "Preset Overlay",
                        "verbose_name_plural": "Preset Overlays",
                        "ordering": ["preset", "segment", "order"],
                        "db_table": "media_files_presetoverlay",
                    },
                ),
                migrations.CreateModel(
                    name="VideoEncodePreset",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("name", models.CharField(help_text='Unique name for this encoding preset (e.g., "1080p25_9000k")', max_length=255, unique=True, verbose_name="Preset Name")),
                        ("display_name", models.CharField(blank=True, help_text="Human-readable name shown in UI (auto-generated if empty)", max_length=255, verbose_name="Display Name")),
                        ("description", models.TextField(blank=True, help_text="Optional description of this encoding preset", verbose_name="Description")),
                        ("width", models.IntegerField(help_text="Video width in pixels", verbose_name="Width")),
                        ("height", models.IntegerField(help_text="Video height in pixels", verbose_name="Height")),
                        ("fps", models.IntegerField(help_text="Frames per second", verbose_name="FPS")),
                        ("vcodec", models.CharField(default="libx264", help_text='Video codec (e.g., "libx264")', max_length=50, verbose_name="Video Codec")),
                        ("video_bitrate_k", models.IntegerField(default=9000, help_text="Video bitrate in kilobits per second", verbose_name="Video Bitrate (kbps)")),
                        ("acodec", models.CharField(default="aac", help_text='Audio codec (e.g., "aac")', max_length=50, verbose_name="Audio Codec")),
                        ("audio_bitrate_k", models.IntegerField(default=192, help_text="Audio bitrate in kilobits per second", verbose_name="Audio Bitrate (kbps)")),
                        ("audio_sample_rate", models.IntegerField(default=48000, help_text="Audio sample rate in Hz", verbose_name="Audio Sample Rate (Hz)")),
                        ("audio_channels", models.IntegerField(default=2, help_text="Number of audio channels", verbose_name="Audio Channels")),
                        ("pix_fmt", models.CharField(default="yuv420p", help_text='Pixel format (e.g., "yuv420p")', max_length=50, verbose_name="Pixel Format")),
                        ("x264_preset", models.CharField(default="veryfast", help_text='x264 encoding preset (e.g., "veryfast", "medium", "slow")', max_length=50, verbose_name="x264 Preset")),
                        ("x264_profile", models.CharField(default="high", help_text='x264 profile (e.g., "baseline", "main", "high")', max_length=50, verbose_name="x264 Profile")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        "verbose_name": "Video Encode Preset",
                        "verbose_name_plural": "Video Encode Presets",
                        "ordering": ["name"],
                        "db_table": "media_files_videoencodepreset",
                    },
                ),
            ],
        ),
        migrations.RunPython(move_content_types_to_tools, move_content_types_back_to_media_files),
    ]

