# Generated by Django 5.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0019_move_video_presets_to_tools'),
        ('tools', '0005_video_presets_from_media_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsconfig',
            name='audio_normalize_input_storage',
            field=models.ForeignKey(
                blank=True,
                help_text='Storage location for input base path. Overrides the path below when set.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='media_files.storagelocation',
                verbose_name='Audio Normalize Input Storage',
            ),
        ),
        migrations.AddField(
            model_name='toolsconfig',
            name='audio_normalize_output_storage',
            field=models.ForeignKey(
                blank=True,
                help_text='Storage location for output directory. Overrides the path below when set.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='media_files.storagelocation',
                verbose_name='Audio Normalize Output Storage',
            ),
        ),
        migrations.AddField(
            model_name='audionormalizejob',
            name='output_path_external',
            field=models.CharField(
                blank=True,
                help_text='Absolute path when output was written outside MEDIA_ROOT (e.g. to a storage location).',
                max_length=1000,
                verbose_name='Output Path (external)',
            ),
        ),
        migrations.AlterField(
            model_name='toolsconfig',
            name='audio_normalize_input_path',
            field=models.CharField(
                default='',
                help_text='Base path when no storage is selected. Used for upload dedup and similar.',
                max_length=500,
                verbose_name='Audio Normalize Input Path',
            ),
        ),
        migrations.AlterField(
            model_name='toolsconfig',
            name='audio_normalize_output_path',
            field=models.CharField(
                default='',
                help_text='Base path when no storage is selected. Empty = next to input. If storage is set, output can be outside MEDIA_ROOT.',
                max_length=500,
                verbose_name='Audio Normalize Output Path',
            ),
        ),
    ]
