# Generated by Django 5.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0019_move_video_presets_to_tools'),
        ('tools', '0006_audio_normalize_storage_and_external_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsconfig',
            name='storage_path_storage',
            field=models.ForeignKey(
                blank=True,
                help_text='Storage location for uploads. Overrides the path below when set.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='media_files.storagelocation',
                verbose_name='Storage Path (Storage Location)',
            ),
        ),
        migrations.AddField(
            model_name='toolsconfig',
            name='output_path_storage',
            field=models.ForeignKey(
                blank=True,
                help_text='Storage location for generated videos. Overrides the path below when set.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='media_files.storagelocation',
                verbose_name='Output Path (Storage Location)',
            ),
        ),
        migrations.AlterField(
            model_name='toolsconfig',
            name='storage_path',
            field=models.CharField(
                help_text='Base path when no storage is selected. For storing uploaded media files.',
                max_length=500,
                verbose_name='Storage Path',
            ),
        ),
        migrations.AlterField(
            model_name='toolsconfig',
            name='output_path',
            field=models.CharField(
                help_text='Base path when no storage is selected. For storing generated videos.',
                max_length=500,
                verbose_name='Output Path',
            ),
        ),
    ]
