# Generated by Django 5.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_storage_path_output_path_storage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsconfig',
            name='storage_path_storage',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional. Storage location for uploads. Overrides the path below when set.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='media_files.storagelocation',
                verbose_name='Storage Path (Storage Location)',
            ),
        ),
        migrations.AlterField(
            model_name='toolsconfig',
            name='storage_path',
            field=models.CharField(
                help_text='Required when no Storage Location is selected. Base path for storing uploaded media files.',
                max_length=500,
                verbose_name='Storage Path',
            ),
        ),
        migrations.AlterField(
            model_name='toolsconfig',
            name='output_path_storage',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional. Storage location for generated videos. Overrides the path below when set.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='media_files.storagelocation',
                verbose_name='Output Path (Storage Location)',
            ),
        ),
        migrations.AlterField(
            model_name='toolsconfig',
            name='output_path',
            field=models.CharField(
                help_text='Required when no Storage Location is selected. Base path for storing generated videos.',
                max_length=500,
                verbose_name='Output Path',
            ),
        ),
        migrations.AlterField(
            model_name='toolsconfig',
            name='audio_normalize_input_storage',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional. Storage location for input base path. Overrides the path below when set.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='media_files.storagelocation',
                verbose_name='Audio Normalize Input Storage',
            ),
        ),
        migrations.AlterField(
            model_name='toolsconfig',
            name='audio_normalize_input_path',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Base path when no storage is selected. Used for upload dedup and similar. Can be empty.',
                max_length=500,
                verbose_name='Audio Normalize Input Path',
            ),
        ),
        migrations.AlterField(
            model_name='toolsconfig',
            name='audio_normalize_output_storage',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional. Storage location for output directory. Overrides the path below when set.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='media_files.storagelocation',
                verbose_name='Audio Normalize Output Storage',
            ),
        ),
        migrations.AlterField(
            model_name='toolsconfig',
            name='audio_normalize_output_path',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Base path when no storage is selected. Empty = next to input. Can be left empty. If storage is set, output can be outside MEDIA_ROOT.',
                max_length=500,
                verbose_name='Audio Normalize Output Path',
            ),
        ),
    ]
