# Generated by Django 5.2.7 on 2026-01-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_toolsconfig_help_text_and_audio_path_blank'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='audionormalizejob',
            new_name='tools_audio_created_ff2115_idx',
            old_name='tools_audio_created_7c0c12_idx',
        ),
        migrations.RenameIndex(
            model_name='audionormalizejob',
            new_name='tools_audio_status_61ef12_idx',
            old_name='tools_audio_status_98c4e3_idx',
        ),
        migrations.AlterField(
            model_name='presetoverlay',
            name='animation',
            field=models.CharField(choices=[('none', 'None'), ('fade', 'Fade'), ('slide_up', 'Slide Up'), ('slide_left', 'Slide Left'), ('slide_right', 'Slide Right'), ('slide_down', 'Slide Down'), ('zoom_in', 'Zoom In'), ('zoom_out', 'Zoom Out')], default='fade', max_length=20, verbose_name='Animation'),
        ),
    ]
