# Generated by Django 5.2.7 on 2026-01-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_audio_normalize_input_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsconfig',
            name='arnndn_model_path',
            field=models.CharField(blank=True, default='', help_text='Path to RNN model file (.rnnn) for neural network denoising (arnndn filter). Leave empty to use FFT-based denoising (afftdn).', max_length=500, verbose_name='ARNNDN Model Path'),
        ),
    ]
