# Generated by Django 5.2.7 on 2026-01-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_add_arnndn_model_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolsconfig',
            name='arnndn_model_path',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Default path to RNN model file (.rnnn) for neural network denoising (arnndn filter). System automatically detects and uses recommended models (std.rnnn, bd.rnnn, lq.rnnn) from tools/rnn_models/ directory. Leave empty to use FFT-based denoising (afftdn).',
                max_length=500,
                verbose_name='ARNNDN Model Path'
            ),
        ),
    ]
