# Generated by Django 6.0.6 on 2026-06-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_add_duration_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshowproject',
            name='audio_trim_mode',
            field=models.CharField(choices=[('fade', 'Fade Out'), ('trim', 'Trim to Fit')], default='fade', help_text='What to do when images are shorter than music', max_length=10, verbose_name='Audio Trim Mode'),
        ),
        migrations.AlterField(
            model_name='slideshowproject',
            name='duration_mode',
            field=models.CharField(choices=[('music', 'By Music Duration'), ('images', 'By Image Duration')], default='music', help_text='How to calculate video duration', max_length=10, verbose_name='Duration Mode'),
        ),
    ]
