# Generated by Django 6.0.6 on 2026-06-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_alter_slideshowproject_audio_trim_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolsconfig',
            name='reel_default_mediathek_zeile1',
            field=models.CharField(blank=True, default='Mehr Beiträge aus deiner Region.', help_text='Default first line of the mediathek badge.', max_length=255, verbose_name='Reel mediathek line 1'),
        ),
        migrations.AddField(
            model_name='toolsconfig',
            name='reel_default_mediathek_zeile2',
            field=models.CharField(blank=True, default='Jetzt in der Mediathek — lokalmedial.de', help_text='Default second line of the mediathek badge.', max_length=255, verbose_name='Reel mediathek line 2'),
        ),
        migrations.AddField(
            model_name='toolsconfig',
            name='reel_output_name_pattern',
            field=models.CharField(blank=True, default='{number}_Programmvorschau_Reel_{date:%y%m%d}', help_text='Python format string with {number} and {date} used to prefill the output name, e.g. {number}_Programmvorschau_Reel_{date:%y%m%d}.', max_length=255, verbose_name='Reel output filename pattern'),
        ),
        migrations.AddField(
            model_name='toolsconfig',
            name='reel_render_api_key',
            field=models.CharField(blank=True, default='', help_text='Sent as X-API-Key header to the reel renderer.', max_length=255, verbose_name='Reel render API key'),
        ),
        migrations.AddField(
            model_name='toolsconfig',
            name='reel_render_timeout',
            field=models.PositiveIntegerField(default=30, help_text='HTTP read timeout for reel render/start requests.', verbose_name='Reel render timeout (seconds)'),
        ),
        migrations.AddField(
            model_name='toolsconfig',
            name='reel_render_url',
            field=models.URLField(blank=True, default='', help_text='Base URL of the external reel renderer, e.g. http://192.168.122.14:8011', verbose_name='Reel render URL'),
        ),
        migrations.AddField(
            model_name='toolsconfig',
            name='reel_studio_enabled',
            field=models.BooleanField(default=False, help_text='Master switch for the Reel Studio tool. When off, the tool card, page and the license admin action are hidden and disabled.', verbose_name='Reel Studio enabled'),
        ),
    ]
