#!/bin/bash
# Generate docker-compose.override.yml based on environment variables
# This allows individual servers to mount custom volumes without modifying git-tracked files

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Try to detect production directory from current working directory or script location
# If script is called from production directory, use that
# Otherwise, try to find it relative to script location
if [ -f "docker-compose.yml" ] || [ -f ".env" ]; then
    PRODUCTION_DIR="$(pwd)"
else
    # Try parent of parent (assuming script is in deployment/scripts/)
    PRODUCTION_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
    # If that doesn't work, try to find it
    if [ ! -f "$PRODUCTION_DIR/docker-compose.yml" ] && [ ! -f "$PRODUCTION_DIR/.env" ]; then
        # Look for production directory in common locations
        if [ -d "$(dirname "$SCRIPT_DIR")/../../ok_tools_production" ]; then
            PRODUCTION_DIR="$(dirname "$SCRIPT_DIR")/../../ok_tools_production"
        fi
    fi
fi
OVERRIDE_FILE="$PRODUCTION_DIR/docker-compose.override.yml"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Load .env file if it exists
ENV_FILE="$PRODUCTION_DIR/.env"
if [ -f "$ENV_FILE" ]; then
    print_info "Loading environment variables from $ENV_FILE"
    set -a
    # Use a safer method to load .env file that handles values with spaces
    # This exports variables while ignoring comments and empty lines
    while IFS= read -r line || [ -n "$line" ]; do
        # Skip comments and empty lines
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${line// }" ]] && continue
        # Export variable, handling values with spaces and special characters
        if [[ "$line" =~ ^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
            var_name="${BASH_REMATCH[1]}"
            var_value="${BASH_REMATCH[2]}"
            # Remove leading/trailing whitespace and quotes if present
            var_value="${var_value#"${var_value%%[![:space:]]*}"}"
            var_value="${var_value%"${var_value##*[![:space:]]}"}"
            var_value="${var_value#\"}"
            var_value="${var_value%\"}"
            var_value="${var_value#\'}"
            var_value="${var_value%\'}"
            # Export the variable
            export "$var_name=$var_value"
        fi
    done < "$ENV_FILE"
    set +a
fi

# Check if we're in the production directory
if [ ! -f "$PRODUCTION_DIR/docker-compose.yml" ] && [ ! -f "$PRODUCTION_DIR/docker-compose.production.yml" ]; then
    print_error "Production directory not found. Expected docker-compose.yml or docker-compose.production.yml in: $PRODUCTION_DIR"
    exit 1
fi

# Start building override file
print_info "Generating docker-compose.override.yml..."

cat > "$OVERRIDE_FILE" << 'EOF'
# This file is auto-generated by generate-override.sh
# DO NOT edit manually - it will be overwritten
# To customize mounts, set environment variables in .env:
#   NAS_MOUNT_PATH=/mnt/nas
#   NAS_MOUNT_MODE=ro
#   CUSTOM_MOUNT_1_PATH=/path/to/mount1
#   CUSTOM_MOUNT_1_CONTAINER_PATH=/container/path1
#   CUSTOM_MOUNT_1_MODE=ro
#   etc.

version: '3.8'

services:
EOF

# Function to add volume mount to a service
add_volume_to_service() {
    local service_name=$1
    local host_path=$2
    local container_path=$3
    local mode=${4:-ro}
    
    # Validate paths
    if [ -z "$host_path" ] || [ -z "$container_path" ]; then
        return 1
    fi
    
    # Check if host path exists (warn if not)
    if [ ! -e "$host_path" ]; then
        print_warning "Host path does not exist: $host_path (will be created if needed)"
    fi
    
    # Add volume to service
    cat >> "$OVERRIDE_FILE" << EOF
  ${service_name}:
    volumes:
      - ${host_path}:${container_path}:${mode}
EOF
}

# Check for NAS mount
if [ -n "${NAS_MOUNT_PATH:-}" ]; then
    NAS_MODE="${NAS_MOUNT_MODE:-ro}"
    print_info "Adding NAS mount: ${NAS_MOUNT_PATH} -> /mnt/nas (${NAS_MODE})"
    
    # Add to web and celery_worker
    add_volume_to_service "web" "$NAS_MOUNT_PATH" "/mnt/nas" "$NAS_MODE"
    add_volume_to_service "celery_worker" "$NAS_MOUNT_PATH" "/mnt/nas" "$NAS_MODE"
else
    print_info "NAS_MOUNT_PATH not set - skipping NAS mount"
fi

# Check for custom mounts (CUSTOM_MOUNT_1_PATH, CUSTOM_MOUNT_2_PATH, etc.)
MOUNT_COUNT=0
for i in {1..10}; do
    MOUNT_PATH_VAR="CUSTOM_MOUNT_${i}_PATH"
    MOUNT_CONTAINER_VAR="CUSTOM_MOUNT_${i}_CONTAINER_PATH"
    MOUNT_MODE_VAR="CUSTOM_MOUNT_${i}_MODE"
    MOUNT_SERVICES_VAR="CUSTOM_MOUNT_${i}_SERVICES"
    
    MOUNT_PATH="${!MOUNT_PATH_VAR:-}"
    MOUNT_CONTAINER="${!MOUNT_CONTAINER_VAR:-}"
    MOUNT_MODE="${!MOUNT_MODE_VAR:-ro}"
    MOUNT_SERVICES="${!MOUNT_SERVICES_VAR:-web,celery_worker}"
    
    if [ -n "$MOUNT_PATH" ] && [ -n "$MOUNT_CONTAINER" ]; then
        MOUNT_COUNT=$((MOUNT_COUNT + 1))
        print_info "Adding custom mount #${i}: ${MOUNT_PATH} -> ${MOUNT_CONTAINER} (${MOUNT_MODE})"
        
        # Add to specified services (comma-separated)
        IFS=',' read -ra SERVICES <<< "$MOUNT_SERVICES"
        for service in "${SERVICES[@]}"; do
            service=$(echo "$service" | xargs) # trim whitespace
            add_volume_to_service "$service" "$MOUNT_PATH" "$MOUNT_CONTAINER" "$MOUNT_MODE"
        done
    fi
done

if [ $MOUNT_COUNT -eq 0 ]; then
    print_info "No custom mounts configured"
fi

# If no volumes were added, create minimal override file
if ! grep -q "volumes:" "$OVERRIDE_FILE"; then
    print_info "No additional volumes to mount - creating empty override file"
    cat > "$OVERRIDE_FILE" << 'EOF'
# This file is auto-generated by generate-override.sh
# No additional volumes configured
# To add mounts, set environment variables in .env:
#   NAS_MOUNT_PATH=/mnt/nas
#   CUSTOM_MOUNT_1_PATH=/path/to/mount1
#   CUSTOM_MOUNT_1_CONTAINER_PATH=/container/path1
#   etc.

version: '3.8'

services: {}
EOF
else
    print_info "Override file generated successfully"
fi

print_info "Override file location: $OVERRIDE_FILE"
print_info "To apply changes, run: docker compose -f docker-compose.production.yml -f docker-compose.override.yml up -d"

