#!/bin/bash
# Install the ok-tools systemd unit so the Docker Compose stack starts on boot
# and only after its NAS / custom bind-mount host paths are mounted.
#
# What it does:
#   1. Renders deployment/systemd/ok-tools.service into
#      /etc/systemd/system/ok-tools.service (substituting the production dir and
#      the docker binary path).
#   2. Collects the host mount paths from .env (NAS_MOUNT_PATH + CUSTOM_MOUNT_*_PATH)
#      and writes them as RequiresMountsFor= into the drop-in
#      /etc/systemd/system/ok-tools.service.d/10-mounts.conf
#   3. daemon-reload + enable (optionally start) the service.
#
# Run as root:
#   sudo deployment/scripts/install-systemd.sh
#
# Environment overrides:
#   PRODUCTION_DIR   Path to the production dir (default: ../ok_tools_production)
#   SERVICE_NAME     systemd unit name (default: ok-tools)
#   EXTRA_MOUNTS     Space-separated extra paths to require (e.g. /mnt/austausch_export)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"

SERVICE_NAME="${SERVICE_NAME:-ok-tools}"
TEMPLATE="$PROJECT_DIR/deployment/systemd/ok-tools.service"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

if [ "$(id -u)" -ne 0 ]; then
    error "This script must be run as root (use sudo)."
    exit 1
fi

# --- Resolve production directory -------------------------------------------
if [ -z "${PRODUCTION_DIR:-}" ]; then
    PRODUCTION_DIR="$(dirname "$PROJECT_DIR")/ok_tools_production"
fi
if [ ! -f "$PRODUCTION_DIR/docker-compose.yml" ]; then
    error "docker-compose.yml not found in PRODUCTION_DIR=$PRODUCTION_DIR"
    error "Run the main install.sh first, or set PRODUCTION_DIR explicitly."
    exit 1
fi
info "Production directory: $PRODUCTION_DIR"

# --- Locate docker binary ----------------------------------------------------
DOCKER_BIN="$(command -v docker || true)"
if [ -z "$DOCKER_BIN" ]; then
    error "docker binary not found in PATH."
    exit 1
fi
if ! "$DOCKER_BIN" compose version >/dev/null 2>&1; then
    error "'docker compose' (v2 plugin) is not available."
    exit 1
fi
info "Docker binary: $DOCKER_BIN"

# --- Collect host mount paths from .env -------------------------------------
declare -a MOUNT_PATHS=()
ENV_FILE="$PRODUCTION_DIR/.env"
if [ -f "$ENV_FILE" ]; then
    info "Reading mount paths from $ENV_FILE"
    # Parse .env safely without sourcing it.
    while IFS= read -r line || [ -n "$line" ]; do
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${line// }" ]] && continue
        if [[ "$line" =~ ^[[:space:]]*(NAS_MOUNT_PATH|CUSTOM_MOUNT_[0-9]+_PATH)=(.*)$ ]]; then
            val="${BASH_REMATCH[2]}"
            # strip surrounding whitespace and quotes
            val="${val#"${val%%[![:space:]]*}"}"; val="${val%"${val##*[![:space:]]}"}"
            val="${val#\"}"; val="${val%\"}"; val="${val#\'}"; val="${val%\'}"
            [ -n "$val" ] && MOUNT_PATHS+=("$val")
        fi
    done < "$ENV_FILE"
else
    warn "No .env found at $ENV_FILE - no mount paths auto-detected."
fi

# Allow the operator to add paths that are not modelled in .env
# (e.g. the austausch export target).
if [ -n "${EXTRA_MOUNTS:-}" ]; then
    for p in $EXTRA_MOUNTS; do
        MOUNT_PATHS+=("$p")
    done
fi

# --- Render the unit file ----------------------------------------------------
UNIT_DEST="/etc/systemd/system/${SERVICE_NAME}.service"
info "Writing unit: $UNIT_DEST"
sed -e "s|__PRODUCTION_DIR__|${PRODUCTION_DIR}|g" \
    -e "s|__DOCKER_BIN__|${DOCKER_BIN}|g" \
    "$TEMPLATE" > "$UNIT_DEST"

# --- Render the mounts drop-in ----------------------------------------------
DROPIN_DIR="/etc/systemd/system/${SERVICE_NAME}.service.d"
DROPIN="$DROPIN_DIR/10-mounts.conf"
mkdir -p "$DROPIN_DIR"
if [ ${#MOUNT_PATHS[@]} -gt 0 ]; then
    # De-duplicate while preserving order.
    declare -a UNIQUE=()
    for p in "${MOUNT_PATHS[@]}"; do
        skip=""
        for u in "${UNIQUE[@]}"; do [ "$u" = "$p" ] && skip=1 && break; done
        [ -z "$skip" ] && UNIQUE+=("$p")
    done
    info "Requiring mounts: ${UNIQUE[*]}"
    {
        echo "# Auto-generated by install-systemd.sh from .env - do not edit by hand."
        echo "# Re-run install-systemd.sh after changing mount paths in .env."
        echo "[Unit]"
        echo "RequiresMountsFor=${UNIQUE[*]}"
    } > "$DROPIN"
else
    warn "No mount paths detected - writing empty drop-in."
    warn "If the stack relies on NAS/other mounts, set NAS_MOUNT_PATH / CUSTOM_MOUNT_*_PATH"
    warn "in .env (or pass EXTRA_MOUNTS=...) and re-run this script."
    {
        echo "# Auto-generated by install-systemd.sh - no mount paths were detected."
        echo "[Unit]"
    } > "$DROPIN"
fi

# --- Reload + enable ---------------------------------------------------------
info "Reloading systemd..."
systemctl daemon-reload
info "Enabling ${SERVICE_NAME}.service (start on boot)..."
systemctl enable "${SERVICE_NAME}.service"

echo ""
info "Done. The stack will start on boot after its mounts are available."
echo "  Start now:      sudo systemctl start ${SERVICE_NAME}"
echo "  Status:         systemctl status ${SERVICE_NAME}"
echo "  Verify deps:    systemctl show ${SERVICE_NAME} -p RequiresMountsFor -p After"
echo "  Stop:           sudo systemctl stop ${SERVICE_NAME}"
echo ""
warn "Note: this unit runs 'docker compose up -d/down'. Avoid also running the"
warn "start.sh/stop.sh helpers manually while the unit manages the stack, to"
warn "prevent the two from fighting over container state."
