# Generated by Django 6.0.6 on 2026-08-09 00:32

from django.conf import settings
from django.db import migrations
from django.db import models
import datetime
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Master switch for the whole notification system.', verbose_name='Enabled')),
                ('digest_time', models.TimeField(default=datetime.time(10, 0), help_text='When the day marker is built. Nothing is sent by email.', verbose_name='Daily summary time')),
                ('retention_days', models.PositiveIntegerField(default=90, help_text='Events older than this are deleted by the cleanup task.', verbose_name='Retention (days)')),
            ],
            options={
                'verbose_name': 'Notification Configuration',
                'verbose_name_plural': 'Notification Configuration',
            },
        ),
        migrations.CreateModel(
            name='NotificationEventTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Event type')),
                ('enabled', models.BooleanField(default=True, help_text='When off, the check is not executed and nobody sees it.', verbose_name='Enabled')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
            ],
            options={
                'verbose_name': 'Notification event type',
                'verbose_name_plural': 'Notification event types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=50, verbose_name='Module')),
                ('event_type', models.CharField(db_index=True, help_text='Code of the event type declared in the registry.', max_length=100, verbose_name='Event type')),
                ('category', models.CharField(choices=[('action_required', 'Action required'), ('info', 'For information'), ('problem', 'Problem')], default='info', max_length=20, verbose_name='Category')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Occurred at')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object id')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Data used to render the message in the reader language.', verbose_name='Payload')),
                ('dedup_key', models.CharField(help_text='Prevents duplicates when a scan or a signal runs twice.', max_length=255, unique=True, verbose_name='Deduplication key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
            ],
            options={
                'verbose_name': 'Notification event',
                'verbose_name_plural': 'Notification events',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50, verbose_name='Module')),
                ('event_type', models.CharField(default='*', help_text='Use * to subscribe to the whole module.', max_length=100, verbose_name='Event type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification subscription',
                'verbose_name_plural': 'Notification subscriptions',
                'ordering': ['module', 'event_type'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read at')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dismissed at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='notifications.notificationevent', verbose_name='Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User notification',
                'verbose_name_plural': 'User notifications',
                'ordering': ['-event__occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Last seen at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_state', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification read state',
                'verbose_name_plural': 'Notification read states',
            },
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['module', '-occurred_at'], name='notif_module_occurred_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='notif_type_occurred_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'module', 'event_type')},
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'dismissed_at'], name='notif_user_dismissed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('user', 'event')},
        ),
    ]
