# Generated by Django 6.0.6 on 2026-08-09 08:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsuppression'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, help_text='Hidden from the list until this moment.', null=True, verbose_name='Snoozed until'),
        ),
    ]
