# Generated by Django 6.0.6 on 2026-08-20 16:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_usernotification_snoozed_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='delegated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delegated at'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='delegated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_delegations', to=settings.AUTH_USER_MODEL, verbose_name='Delegated by'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='delegated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Delegated to'),
        ),
        migrations.CreateModel(
            name='ManualReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Shown as the reminder itself, e.g. "Send the TV listings to the newspaper".', max_length=200, verbose_name='Title')),
                ('message', models.TextField(blank=True, help_text='Optional: what exactly has to be done.', verbose_name='Details')),
                ('url', models.URLField(blank=True, help_text='Optional: where the work is done.', verbose_name='Link')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('frequency', models.CharField(choices=[('once', 'Once, on a date'), ('weekly', 'Every week'), ('monthly', 'Every month')], default='weekly', max_length=10, verbose_name='Repeat')),
                ('run_date', models.DateField(blank=True, help_text='Only for "Once, on a date".', null=True, verbose_name='Date')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Only for "Every week".', null=True, verbose_name='Weekday')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Only for "Every month". A month that is shorter uses its last day.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Day of month')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Manual reminder',
                'verbose_name_plural': 'Manual reminders',
                'ordering': ['title'],
            },
        ),
    ]
