# Generated by Django 5.2 on 2026-05-28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('planung', '0002_plantemplate_planchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanungConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playout_import_url', models.URLField(blank=True, help_text='External playout endpoint, e.g. http://192.168.88.50/api/media/import', verbose_name='Playout import URL')),
                ('playout_import_api_key', models.CharField(blank=True, help_text='API key sent as X-API-Key when planned media metadata is exported.', max_length=255, verbose_name='Playout import API key')),
                ('playout_import_timeout', models.PositiveIntegerField(default=10, help_text='HTTP timeout for playout metadata import requests.', verbose_name='Playout import timeout (seconds)')),
            ],
            options={
                'verbose_name': 'Planning Configuration',
                'verbose_name_plural': 'Planning Configuration',
            },
        ),
    ]
