# Generated by Django 5.2 on 2026-05-28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('planung', '0003_planungconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='planungconfig',
            name='playout_missing_url',
            field=models.URLField(blank=True, help_text='Endpoint for files without metadata, e.g. http://192.168.88.50/api/media/import/missing. If empty, /missing is appended to the import URL.', verbose_name='Playout missing metadata URL'),
        ),
        migrations.AddField(
            model_name='planungconfig',
            name='playout_missing_sync_enabled',
            field=models.BooleanField(default=False, help_text='Periodically query playout for files that still need metadata.', verbose_name='Enable periodic missing metadata check'),
        ),
        migrations.AddField(
            model_name='planungconfig',
            name='playout_missing_sync_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='How often Celery Beat should query playout for missing metadata.', verbose_name='Missing metadata check interval (minutes)'),
        ),
        migrations.AddField(
            model_name='planungconfig',
            name='playout_missing_page_size',
            field=models.PositiveIntegerField(default=100, help_text='Number of missing playout files requested per page.', verbose_name='Missing metadata page size'),
        ),
    ]
