# Generated by Django 5.2.7 on 2026-05-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planung', '0004_planungconfig_missing_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='planungconfig',
            name='playout_schedule_url',
            field=models.URLField(blank=True, help_text='External playout schedule endpoint, e.g. http://192.168.88.50/api/schedule/import/oktools', verbose_name='Playout schedule URL'),
        ),
    ]
