# Generated by Django 5.2.7 on 2026-05-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planung', '0005_planungconfig_playout_schedule_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, default='', max_length=255, verbose_name='External ID')),
                ('media_filename', models.CharField(blank=True, default='', max_length=500, verbose_name='Media filename')),
                ('scheduled_start', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled start')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Ended at')),
                ('used_fallback', models.BooleanField(default=False, verbose_name='Used fallback')),
                ('direction', models.CharField(choices=[('inbound_media', 'Inbound media'), ('inbound_schedule', 'Inbound schedule'), ('outbound_air_report', 'Outbound air report')], default='outbound_air_report', max_length=30, verbose_name='Direction')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Raw payload')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Air report',
                'verbose_name_plural': 'Air reports',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IncomingWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Connector ID')),
                ('direction', models.CharField(choices=[('inbound_media', 'Inbound media'), ('inbound_schedule', 'Inbound schedule'), ('outbound_air_report', 'Outbound air report')], max_length=30, verbose_name='Direction')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('processed', models.BooleanField(default=False, help_text='Whether the webhook payload has been processed.', verbose_name='Processed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Incoming webhook log',
                'verbose_name_plural': 'Incoming webhook logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='planungconfig',
            name='webhook_hmac_secret',
            field=models.CharField(blank=True, default='', help_text='Shared secret for HMAC-SHA256 verification of incoming webhooks.', max_length=255, verbose_name='Webhook HMAC secret'),
        ),
    ]
