# Generated by Codex on 2026-06-05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("planung", "0006_airreport_incomingwebhooklog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planungconfig",
            name="anchor_render_url",
            field=models.URLField(
                blank=True,
                help_text="External anchor render endpoint, e.g. http://192.168.88.50:8011/api/anchor",
                verbose_name="Anchor render URL",
            ),
        ),
        migrations.AddField(
            model_name="planungconfig",
            name="anchor_render_api_key",
            field=models.CharField(
                blank=True,
                help_text="API key sent as X-API-Key when the programme preview video is rendered.",
                max_length=255,
                verbose_name="Anchor render API key",
            ),
        ),
        migrations.AddField(
            model_name="planungconfig",
            name="anchor_render_timeout",
            field=models.PositiveIntegerField(
                default=30,
                help_text="HTTP timeout for anchor render requests.",
                verbose_name="Anchor render timeout (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="planungconfig",
            name="anchor_render_wait",
            field=models.BooleanField(
                default=True,
                help_text="Append wait=1 to the render request and wait for the synchronous response.",
                verbose_name="Wait for render result",
            ),
        ),
        migrations.AddField(
            model_name="planungconfig",
            name="anchor_output_filename_pattern",
            field=models.CharField(
                blank=True,
                default="{number}_Programmvorschau_{date:%y%m%d}.mp4",
                help_text="Python format string with {number} and {date}, e.g. {number}_Programmvorschau_{date:%y%m%d}.mp4.",
                max_length=255,
                verbose_name="Anchor output filename pattern",
            ),
        ),
        migrations.AddField(
            model_name="planungconfig",
            name="anchor_playout_path_prefix",
            field=models.CharField(
                blank=True,
                default="playout",
                help_text="NAS-relative prefix sent for videos copied to playout.",
                max_length=255,
                verbose_name="Anchor playout path prefix",
            ),
        ),
        migrations.AddField(
            model_name="planungconfig",
            name="anchor_default_placeholder_video",
            field=models.CharField(
                blank=True,
                help_text="NAS-relative fallback video path, e.g. playout/placeholder/default.mp4.",
                max_length=500,
                verbose_name="Anchor default placeholder video",
            ),
        ),
        migrations.AddField(
            model_name="planungconfig",
            name="anchor_placeholder_rules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of rules. Supported match values: live, title_prefix. Each rule needs a video path; title_prefix rules also need prefix.",
                verbose_name="Anchor placeholder rules",
            ),
        ),
    ]
