# Generated by Django 5.2.7 on 2026-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planung', '0007_planungconfig_anchor_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='planungconfig',
            name='anchor_output_playout_directory',
            field=models.CharField(blank=True, default='003_Programmvorschau', help_text='Directory inside the playout storage where rendered programme preview files are written.', max_length=500, verbose_name='Anchor output playout directory'),
        ),
    ]
