# Generated by Django 5.2.7 on 2026-06-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planung', '0008_planungconfig_anchor_output_playout_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='planungconfig',
            name='anchor_contribution_duration_seconds',
            field=models.PositiveIntegerField(default=20, help_text='Preview clip length sent as durationInSeconds for each anchor contribution.', verbose_name='Anchor contribution duration (seconds)'),
        ),
    ]
