# Generated by Django 5.2.7 on 2026-06-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planung', '0009_planungconfig_anchor_contribution_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagesplan',
            name='copy_task_id',
            field=models.CharField(blank=True, default='', help_text='Celery task ID for copy_videos_for_plan', max_length=255),
        ),
    ]
