# Generated by Django 6.0.6 on 2026-06-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planung', '0010_add_copy_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planungconfig',
            name='anchor_placeholder_rules',
            field=models.JSONField(blank=True, default=list, help_text='List of rules. Supported match values: live, title_prefix, title_contains. Each rule needs a video path; title_prefix rules also need prefix; title_contains rules also need contains.', verbose_name='Anchor placeholder rules'),
        ),
    ]
